title: ExecutionElementConfig
type: object
required:
- steps
properties:
  steps:
    type: array
    items:
      $ref: execution-wrapper-config.yaml
    maxItems: 256
    minItems: 1
  description:
    desc: This is the description for ExecutionElementConfig
$schema: http://json-schema.org/draft-07/schema#
