# V0 version of the template
template:
  templateRef: tpl
  versionLabel: "0"
  templateInputs:
    type: ShellScript
    spec:
      environmentVariables:
        - name: abc
          type: String
          value: <+input>
    timeout: <+input>
---

# Pipeline v1 with vo version of the templates
version: 1

# Input variables are defined independently in the yaml
inputs:
  env:
    type: string
    required: true
    default: qa
  timeout:
    type: string
    required: true
    default: 10m
  
stages:
  - type: Custom
    spec:
      steps:
        - type: template
          spec:
            name: tpl
            versionLabel: "0"
            inputs:
              timeout: <+inputs.timeout>
              type: ShellScript
              spec:
                environmentVariables:
                  - name: abc
                    type: String
                    value: <+inputs.env>
                    
---

# InputSet 

version: 1
data:
  env: prod
  timeout: 30m