title: FlagConfigurationStepInfo
allOf:
- $ref: ../../common/step-spec-type.yaml
- type: object
  required:
  - env
  - feature
  - instructions
  properties:
    env:
      type: string
    feature:
      type: string
    instructions:
      oneOf:
      - type: array
        items:
          $ref: patch-instruction.yaml
      - type: string
        pattern: (<\+.+>.*)
        minLength: 1
$schema: http://json-schema.org/draft-07/schema#
type: object
