title: SscaOpaPolicyConfig
type: object
required:
- policySet
properties:
  policySet:
    type: string
  description:
    desc: The reference of the SBOM OPA policy set.
$schema: http://json-schema.org/draft-07/schema#
