title: TemplateLinkConfig
type: object
required:
- ref
properties:
  inputs:
    $ref: ../../common/json-node.yaml
  ref:
    type: string
  variables:
    $ref: ../../common/json-node.yaml
$schema: http://json-schema.org/draft-07/schema#
