title: TemplateLinkConfigV2
type: object
required:
  - name
  - version
properties:
  inputs:
    $ref: ../../common/json-node.yaml
  name:
    type: string
  variables:
    $ref: ../../common/json-node.yaml
  version:
    type: string
    pattern: ^[0-9a-zA-Z][^\s/&]{0,63}$
  description:
    desc: This is the description for TemplateLinkConfig
$schema: http://json-schema.org/draft-07/schema#