title: TemplateLinkConfig
type: object
required:
- ref
properties:
  inputs:
    type: object
    description: inputs to be used in the linked template
    additionalProperties:
      anyOf:
        - string
        - array
        - list
        - object
        - boolean
    propertyNames:
      pattern: "^[a-zA-Z_][0-9a-zA-Z_\\.$-]{0,127}$"
  ref:
    type: string
$schema: http://json-schema.org/draft-07/schema#
