title: ArtifactListConfig
type: object
properties:
  primary:
    $ref: primary-artifact.yaml
  sidecars:
    type: array
    items:
      $ref: sidecar-artifact-wrapper.yaml
  description:
    desc: This is the description for ArtifactListConfig
$schema: http://json-schema.org/draft-07/schema#
