title: ConfigFileWrapper
type: object
properties:
  configFile:
    $ref: config-file.yaml
  description:
    desc: This is the description for ConfigFileWrapper
$schema: http://json-schema.org/draft-07/schema#
