title: ConfigFileOverrideSets
type: object
properties:
  configFiles:
    type: array
    items:
      $ref: config-file-wrapper.yaml
  identifier:
    type: string
  description:
    desc: This is the description for ConfigFileOverrideSets
$schema: http://json-schema.org/draft-07/schema#
