title: ConfigFile
type: object
required:
- identifier
- spec
properties:
  identifier:
    type: string
  spec:
    $ref: config-file-attributes.yaml
  description:
    desc: This is the description for ConfigFile
$schema: http://json-schema.org/draft-07/schema#
