title: CustomDeploymentNGVariable
type: object
discriminator: type
properties:
  description:
    type: string
    desc: This is the description for CustomDeploymentNGVariable
  name:
    type: string
  required:
    type: boolean
  type:
    type: string
    enum:
    - String
    - Number
    - Secret
    - Connector
$schema: http://json-schema.org/draft-07/schema#
