title: CustomArtifactConfig
allOf:
- $ref: artifact-config.yaml
- type: object
  required:
  - version
  properties:
    delegateSelectors:
      oneOf:
      - type: array
        items:
          type: string
      - type: string
        pattern: ^<\+input>((\.)((executionInput\(\))|(allowedValues|default|regex)\(.+?\)))*$
        minLength: 1
    inputs:
      type: array
      items:
        oneOf:
        - $ref: ../../common/number-ng-variable.yaml
        - $ref: ../../common/secret-ng-variable.yaml
        - $ref: ../../common/string-ng-variable.yaml
    metadata:
      type: string
    scripts:
      $ref: custom-artifact-scripts.yaml
    timeout:
      type: string
      pattern: ^(([1-9])+\d+[s])|(((([1-9])+\d*[mhwd])+([\s]?\d+[smhwd])*)|(<\+input>.*)|(.*<\+.*>.*)|(^$))$
    version:
      type: string
    versionRegex:
      type: string
$schema: http://json-schema.org/draft-07/schema#
properties:
  description:
    desc: This is the description for CustomArtifactConfig
