title: CustomDeploymentNumberNGVariable
allOf:
- $ref: custom-deployment-ng-variable.yaml
- type: object
  required:
  - value
  properties:
    name:
      type: string
      pattern: ^[a-zA-Z_][0-9a-zA-Z_]{0,127}$
    type:
      type: string
      enum:
      - Number
    value:
      oneOf:
      - type: number
        format: double
      - type: string
        pattern: (^[+-]?[0-9]+\.?[0-9]*$|(<\+.+>.*)|^$)
$schema: http://json-schema.org/draft-07/schema#
properties:
  description:
    desc: This is the description for CustomDeploymentNumberNGVariable
