title: CustomDeploymentSecretNGVariable
allOf:
- $ref: custom-deployment-ng-variable.yaml
- type: object
  required:
  - value
  properties:
    name:
      type: string
      pattern: ^[a-zA-Z_][0-9a-zA-Z_]{0,127}$
    type:
      type: string
      enum:
      - Secret
    value:
      type: string
$schema: http://json-schema.org/draft-07/schema#
properties:
  description:
    desc: This is the description for CustomDeploymentSecretNGVariable
