title: DeploymentStageConfig
type: object
required:
- execution
properties:
  customDeploymentRef:
    $ref: step-template-ref.yaml
  deploymentType:
    type: string
    enum:
    - Kubernetes
    - NativeHelm
    - Ssh
    - WinRm
    - ServerlessAwsLambda
    - AzureWebApp
    - AzureFunction
    - CustomDeployment
    - ECS
    - Elastigroup
    - TAS
    - Asg
    - GoogleCloudFunctions
    - AwsLambda
    - AWS_SAM
  environment:
    $ref: environment-yaml-v2.yaml
  environmentGroup:
    $ref: environment-group-yaml.yaml
  environments:
    $ref: environments-yaml.yaml
  execution:
    $ref: execution-element-config.yaml
  gitOpsEnabled:
    type: boolean
  infrastructure:
    $ref: pipeline-infrastructure.yaml
  service:
    $ref: service-yaml-v2.yaml
  serviceConfig:
    $ref: service-config.yaml
  services:
    $ref: services-yaml.yaml
  multiDeploymentConfig:
    $ref: multi-deployment-config.yaml
  description:
    desc: This is the description for DeploymentStageConfig
$schema: http://json-schema.org/draft-07/schema#
allOf:
- if:
    properties:
      deploymentType:
        const: AWS_SAM
  then:
    properties:
      deploymentMetadata:
        $ref: aws-sam-deployment-meta-data.yaml
- if:
    properties:
      deploymentType:
        const: Asg
  then:
    properties:
      deploymentMetadata:
        $ref: asg-deployment-meta-data.yaml
- if:
    properties:
      deploymentType:
        const: AwsLambda
  then:
    properties:
      deploymentMetadata:
        $ref: aws-lambda-deployment-meta-data.yaml
- if:
    properties:
      deploymentType:
        const: AzureWebApp
  then:
    properties:
      deploymentMetadata:
        $ref: azure-web-app-deployment-meta-data.yaml
- if:
    properties:
      deploymentType:
        const: AzureFunction
  then:
    properties:
      deploymentMetadata:
        $ref: azure-function-deployment-meta-data.yaml       
- if:
    properties:
      deploymentType:
        const: CustomDeployment
  then:
    properties:
      deploymentMetadata:
        $ref: custom-deployment-meta-data.yaml
- if:
    properties:
      deploymentType:
        const: ECS
  then:
    properties:
      deploymentMetadata:
        $ref: ecs-deployment-meta-data.yaml
- if:
    properties:
      deploymentType:
        const: Elastigroup
  then:
    properties:
      deploymentMetadata:
        $ref: elasti-group-deployment-meta-data.yaml
- if:
    properties:
      deploymentType:
        const: GoogleCloudFunctions
  then:
    properties:
      deploymentMetadata:
        $ref: google-cloud-function-deployment-meta-data.yaml
- if:
    properties:
      deploymentType:
        const: Kubernetes
  then:
    properties:
      deploymentMetadata:
        $ref: kubernetes-deployment-meta-data.yaml
- if:
    properties:
      deploymentType:
        const: NativeHelm
  then:
    properties:
      deploymentMetadata:
        $ref: native-helm-deployment-meta-data.yaml
- if:
    properties:
      deploymentType:
        const: ServerlessAwsLambda
  then:
    properties:
      deploymentMetadata:
        $ref: serverless-aws-lambda-deployment-meta-data.yaml
- if:
    properties:
      deploymentType:
        const: Ssh
  then:
    properties:
      deploymentMetadata:
        $ref: ssh-deployment-meta-data.yaml
- if:
    properties:
      deploymentType:
        const: TAS
  then:
    properties:
      deploymentMetadata:
        $ref: tas-deployment-meta-data.yaml
- if:
    properties:
      deploymentType:
        const: WinRm
  then:
    properties:
      deploymentMetadata:
        $ref: winrm-deployment-meta-data.yaml
- oneOf:
  - required:
    - serviceConfig
  - required:
    - service
  - required:
    - services
- oneOf:
  - required:
    - environment
  - required:
    - environmentGroup
  - required:
    - environments
  - required:
    - infrastructure
