title: DockerHubArtifactConfig
allOf:
- $ref: artifact-config.yaml
- type: object
  required:
  - connectorRef
  - imagePath
  properties:
    connectorRef:
      type: string
    digest:
      type: string
    imagePath:
      type: string
    tag:
      type: string
    tagRegex:
      type: string
- oneOf:
  - required:
    - tagRegex
  - required:
    - tag
$schema: http://json-schema.org/draft-07/schema#
properties:
  description:
    desc: This is the description for DockerHubArtifactConfig
