title: EnvironmentsYaml
type: object
properties:
  filters:
    oneOf:
    - type: array
      items:
        $ref: filter-yaml.yaml
    - type: string
      pattern: ^<\+input>((\.)((executionInput\(\))|(allowedValues|selectOneFrom|selectManyFrom|default|regex)\(.+?\)))*$
      minLength: 1
  metadata:
    readOnly: true
    $ref: environments-metadata.yaml
  values:
    oneOf:
    - type: array
      items:
        $ref: environment-yaml-v2.yaml
    - type: string
      pattern: (<\+.+>.*)
      minLength: 1
  failureStrategies:
    oneOf:
      - type: array
        items:
          $ref: ../../common/failure-strategy-config.yaml
      - type: string
        pattern: ^<\+input>$
        minLength: 1
  description:
    desc: This is the description for EnvironmentsYaml
$schema: http://json-schema.org/draft-07/schema#
