title: EnvironmentYamlV2
type: object
properties:
  deployToAll:
    oneOf:
    - type: boolean
    - type: string
      pattern: ^<\+input>((\.)((executionInput\(\))|(allowedValues|selectOneFrom|default|regex)\(.+?\)))*$
      minLength: 1
  environmentInputs:
    oneOf:
    - $ref: ../../common/json-node.yaml
    - type: string
      pattern: (^<\+input>((\.)((executionInput\(\))|(allowedValues|selectOneFrom|default|regex)\(.+?\)))*$|^$)
  environmentRef:
    type: string
    pattern: ^(?=\s*\S).*$
  gitBranch:
    type: string
  useFromStage:
    $ref: environment-infra-use-from-stage.yaml
  filters:
    oneOf:
    - type: array
      items:
        $ref: filter-yaml.yaml
    - type: string
      pattern: ^<\+input>((\.)((executionInput\(\))|(allowedValues|selectOneFrom|default|regex)\(.+?\)))*$
      minLength: 1
  gitOpsClusters:
    oneOf:
    - type: array
      items:
        $ref: cluster-yaml.yaml
    - type: string
      pattern: ^<\+input>((\.)((executionInput\(\))|(allowedValues|selectOneFrom|default|regex)\(.+?\)))*$
      minLength: 1
  infrastructureDefinition:
    oneOf:
    - $ref: infra-structure-definition-yaml.yaml
    - type: string
      pattern: (<\+.+>.*)
      minLength: 1
  infrastructureDefinitions:
    oneOf:
    - type: array
      items:
        $ref: infra-structure-definition-yaml.yaml
    - type: string
      pattern: (<\+.+>.*|^$)
  provisioner:
    $ref: execution-element-config.yaml
  serviceOverrideInputs:
    oneOf:
    - $ref: ../../common/json-node.yaml
    - type: string
      pattern: (^<\+input>((\.)((executionInput\(\))|(allowedValues|selectOneFrom|default|regex)\(.+?\)))*$|^$)
  servicesOverrides:
    type: array
    items:
      $ref: service-override-inputs-yaml.yaml
  failureStrategies:
    oneOf:
      - type: array
        items:
          $ref: ../../common/failure-strategy-config.yaml
      - type: string
        pattern: ^<\+input>$
        minLength: 1
  description:
    desc: This is the description for EnvironmentYamlV2
$schema: http://json-schema.org/draft-07/schema#
