title: EnvironmentGroupMetadata
type: object
properties:
  parallel:
    type: boolean
  description:
    desc: This is the description for EnvironmentGroupMetadata
$schema: http://json-schema.org/draft-07/schema#
