title: EnvironmentGroupYaml
type: object
required:
- envGroupRef
properties:
  __uuid:
    type: string
  deployToAll:
    oneOf:
    - type: boolean
    - type: string
      pattern: ^<\+input>((\.)((executionInput\(\))|(allowedValues|selectOneFrom|selectManyFrom|default|regex)\(.+?\)))*$
      minLength: 1
  envGroupRef:
    type: string
    pattern: ^(?=\s*\S).*$
  environments:
    oneOf:
    - type: array
      items:
        $ref: environment-yaml-v2.yaml
    - type: string
      pattern: ^<\+input>((\.)((executionInput\(\))|(allowedValues|selectOneFrom|selectManyFrom|default|regex)\(.+?\)))*$
      minLength: 1
  filters:
    oneOf:
    - type: array
      items:
        $ref: filter-yaml.yaml
    - type: string
      pattern: ^<\+input>((\.)((executionInput\(\))|(allowedValues|selectOneFrom|selectManyFrom|default|regex)\(.+?\)))*$
      minLength: 1
  metadata:
    $ref: environment-group-metadata.yaml
  failureStrategies:
    oneOf:
      - type: array
        items:
          $ref: ../../common/failure-strategy-config.yaml
      - type: string
        pattern: ^<\+input>$
        minLength: 1
  description:
    desc: This is the description for EnvironmentGroupYaml
$schema: http://json-schema.org/draft-07/schema#
