title: ExecutionWrapperConfig
type: object
properties:
  parallel:
    $ref: parallel-step-element-config.yaml
  step:
    oneOf:
    - $ref: ../../common/step-element-config.yaml
    - $ref: ../../steps/cd/asg-blue-green-deploy-step-node.yaml
    - $ref: ../../steps/cd/azure-a-r-m-rollback-step-node.yaml
    - $ref: ../../steps/cd/cloudformation-rollback-step-node.yaml
    - $ref: ../../steps/cd/elastigroup-swap-route-step-node.yaml
    - $ref: ../../steps/cd/terraform-cloud-run-step-node.yaml
    - $ref: ../../steps/cd/asg-rolling-deploy-step-node.yaml
    - $ref: ../../steps/cd/google-functions-rollback-step-node.yaml
    - $ref: ../../steps/cd/fetch-instance-script-step-node.yaml
    - $ref: ../../steps/cd/jenkins-build-step-node.yaml
    - $ref: ../../steps/cd/asg-rolling-rollback-step-node.yaml
    - $ref: ../../steps/cd/asg-canary-delete-step-node.yaml
    - $ref: ../../steps/cd/tas-canary-app-setup-step-node.yaml
    - $ref: ../../steps/cd/tas-rollback-step-node.yaml
    - $ref: ../../steps/cd/aws-lambda-rollback-step-node.yaml
    - $ref: ../../steps/cd/ecs-rolling-deploy-step-node.yaml
    - $ref: ../../steps/cd/google-functions-deploy-step-node.yaml
    - $ref: ../../steps/cd/k8s-rolling-step-node.yaml
    - $ref: ../../steps/cd/google-functions-deploy-without-traffic-step-node.yaml
    - $ref: ../../steps/cd/elastigroup-deploy-step-node.yaml
    - $ref: ../../steps/cd/k8s-apply-step-node.yaml
    - $ref: ../../steps/cd/ecs-blue-green-create-service-step-node.yaml
    - $ref: ../../steps/cd/asg-canary-deploy-step-node.yaml
    - $ref: ../../steps/cd/terraform-destroy-step-node.yaml
    - $ref: ../../steps/cd/azure-web-app-rollback-step-node.yaml
    - $ref: custom-deployment-config.yaml
    - $ref: ../../steps/cd/serverless-aws-lambda-rollback-step-node.yaml
    - $ref: ../../steps/cd/elastigroup-b-g-stage-setup-step-node.yaml
    - $ref: ../../steps/cd/terraform-apply-step-node.yaml
    - $ref: ../../steps/cd/azure-web-app-traffic-shift-step-node.yaml
    - $ref: ../../steps/cd/terragrunt-rollback-step-node.yaml
    - $ref: ../../steps/cd/aws-sam-deploy-step-node.yaml
    - $ref: ../../steps/cd/serverless-aws-lambda-deploy-step-node.yaml
    - $ref: ../../steps/cd/ecs-blue-green-swap-target-groups-step-node.yaml
    - $ref: ../../steps/cd/ecs-run-task-step-node.yaml
    - $ref: ../../steps/cd/cloudformation-delete-stack-step-node.yaml
    - $ref: ../../steps/cd/tas-app-resize-step-node.yaml
    - $ref: ../../steps/cd/shell-script-provision-step-node.yaml
    - $ref: ../../steps/cd/asg-blue-green-rollback-step-node.yaml
    - $ref: ../../steps/cd/tas-rolling-rollback-step-node.yaml
    - $ref: ../../steps/cd/ecs-blue-green-rollback-step-node.yaml
    - $ref: ../../steps/cd/k8s-dry-run-manifest-step-node.yaml
    - $ref: ../../steps/cd/create-p-r-step-node.yaml
    - $ref: ../../steps/cd/k8s-rolling-rollback-step-node.yaml
    - $ref: ../../steps/cd/terragrunt-destroy-step-node.yaml
    - $ref: ../../steps/cd/asg-blue-green-swap-service-step-node.yaml
    - $ref: ../../steps/cd/command-step-node.yaml
    - $ref: ../../steps/cd/ecs-canary-deploy-step-node.yaml
    - $ref: ../../steps/cd/sync-step-node.yaml
    - $ref: ../../steps/cd/azure-web-app-slot-deployment-step-node.yaml
    - $ref: ../../steps/cd/k8s-b-g-swap-services-step-node.yaml
    - $ref: ../../steps/cd/terragrunt-plan-step-node.yaml
    - $ref: ../../steps/cd/aws-lambda-deploy-step-node.yaml
    - $ref: ../../steps/cd/tas-swap-rollback-step-node.yaml
    - $ref: ../../steps/cd/azure-web-app-swap-slot-step-node.yaml
    - $ref: ../../steps/cd/terraform-plan-step-node.yaml
    - $ref: ../../steps/cd/helm-deploy-step-node.yaml
    - $ref: ../../steps/cd/azure-create-b-p-step-node.yaml
    - $ref: ../../steps/cd/ecs-rolling-rollback-step-node.yaml
    - $ref: ../../steps/cd/chaos-step-node.yaml
    - $ref: ../../steps/cd/k8s-delete-step-node.yaml
    - $ref: ../../steps/cd/update-release-repo-step-node.yaml
    - $ref: ../../steps/cd/k8s-blue-green-step-node.yaml
    - $ref: ../../steps/cd/tas-command-step-node.yaml
    - $ref: ../../steps/cd/elastigroup-rollback-step-node.yaml
    - $ref: ../../steps/cd/fetch-linked-apps-step-node.yaml
    - $ref: ../../steps/cd/tas-swap-routes-step-node.yaml
    - $ref: ../../steps/cd/aws-sam-rollback-step-node.yaml
    - $ref: ../../steps/cd/merge-pr-step-node.yaml
    - $ref: ../../steps/cd/tas-rolling-deploy-step-node.yaml
    - $ref: ../../steps/cd/azure-create-a-r-m-resource-step-node.yaml
    - $ref: ../../steps/cd/k8s-canary-delete-step-node.yaml
    - $ref: ../../steps/cd/elastigroup-setup-step-node.yaml
    - $ref: ../../steps/cd/terragrunt-apply-step-node.yaml
    - $ref: ../../steps/cd/tas-b-g-app-setup-step-node.yaml
    - $ref: ../../steps/cd/helm-rollback-step-node.yaml
    - $ref: ../../steps/cd/tas-basic-app-setup-step-node.yaml
    - $ref: ../../steps/cd/terraform-cloud-rollback-step-node.yaml
    - $ref: ../../steps/cd/terraform-rollback-step-node.yaml
    - $ref: ../../steps/cd/cloudformation-create-stack-step-node.yaml
    - $ref: ../../steps/cd/ecs-canary-delete-step-node.yaml
    - $ref: ../../steps/cd/bamboo-build-step-node.yaml
    - $ref: ../../steps/cd/k8s-canary-step-node.yaml
    - $ref: ../../steps/cd/google-functions-traffic-shift-step-node.yaml
    - $ref: ../../steps/cd/k8s-scale-step-node.yaml
    - $ref: ../../steps/cvng/cv-verify-step-node.yaml
    - $ref: ../../steps/pie/http-step-node.yaml
    - $ref: ../../steps/pie/email-step-node.yaml
    - $ref: ../../steps/pie/queue-step-node.yaml
    - $ref: ../../steps/pie/shell-script-step-node.yaml
    - $ref: ../../steps/pie/custom-approval-step-node.yaml
    - $ref: ../../steps/pie/jira-create-step-node.yaml
    - $ref: ../../steps/pie/jira-update-step-node.yaml
    - $ref: ../../steps/pie/template-step-node.yaml
    - $ref: ../../steps/pie/service-now-approval-step-node.yaml
    - $ref: ../../steps/pie/jira-approval-step-node.yaml
    - $ref: ../../steps/pie/harness-approval-step-node.yaml
    - $ref: ../../steps/pie/barrier-step-node.yaml
    - $ref: ../../steps/pie/service-now-create-step-node.yaml
    - $ref: ../../steps/pie/service-now-update-step-node.yaml
    - $ref: ../../steps/pie/service-now-import-set-step-node.yaml
    - $ref: ../../steps/pie/policy-step-node.yaml
    - $ref: ../../steps/pie/wait-step-node.yaml
    - $ref: ../../steps/pie/container-step-node.yaml
  stepGroup:
    $ref: step-group-element-config.yaml
  description:
    desc: This is the description for ExecutionWrapperConfig
$schema: http://json-schema.org/draft-07/schema#
