title: GithubPackagesArtifactConfig
allOf:
- $ref: artifact-config.yaml
- type: object
  required:
  - connectorRef
  - packageName
  - packageType
  properties:
    artifactId:
      type: string
    connectorRef:
      type: string
      minLength: 1
    digest:
      type: string
    extension:
      type: string
    groupId:
      type: string
    org:
      type: string
    packageName:
      type: string
      minLength: 1
    packageType:
      type: string
      enum:
      - npm
      - maven
      - rubygems
      - nuget
      - container
    user:
      type: string
    version:
      type: string
    versionRegex:
      type: string
- oneOf:
  - required:
    - versionRegex
  - required:
    - version
$schema: http://json-schema.org/draft-07/schema#
properties:
  description:
    desc: This is the description for GithubPackagesArtifactConfig
