title: GoogleArtifactRegistryConfig
allOf:
- $ref: artifact-config.yaml
- type: object
  required:
  - connectorRef
  - package
  - project
  - region
  - repositoryName
  - repositoryType
  properties:
    connectorRef:
      type: string
    metadata:
      type: string
    package:
      type: string
    project:
      type: string
    region:
      type: string
    repositoryName:
      type: string
    repositoryType:
      type: string
      enum:
      - docker
    version:
      type: string
    versionRegex:
      type: string
- oneOf:
  - required:
    - versionRegex
  - required:
    - version
$schema: http://json-schema.org/draft-07/schema#
properties:
  description:
    desc: This is the description for GoogleArtifactRegistryConfig
