title: GoogleCloudSourceArtifactConfig
allOf:
- $ref: artifact-config.yaml
- type: object
  required:
  - connectorRef
  - fetchType
  - project
  - repository
  - sourceDirectory
  properties:
    branch:
      type: string
    commitId:
      type: string
    connectorRef:
      type: string
    fetchType:
      type: string
      enum:
      - Branch
      - Commit
      - Tag
    project:
      type: string
    repository:
      type: string
    sourceDirectory:
      type: string
    tag:
      type: string
$schema: http://json-schema.org/draft-07/schema#
properties:
  description:
    desc: This is the description for GoogleCloudSourceArtifactConfig
