title: GoogleCloudSourceArtifactConfig
allOf:
- $ref: artifact-config.yaml
- type: object
  required:
  - connectorRef
  - project
  - repository
  - sourceDirectory
  properties:
    connectorRef:
      type: string
    project:
      type: string
    repository:
      type: string
    sourceDirectory:
      type: string
$schema: http://json-schema.org/draft-07/schema#
properties:
  description:
    desc: This is the description for GoogleCloudSourceArtifactConfig
