title: HarnessRegistryDockerConfig
allOf:
  - $ref: harness-registry-config-spec.yaml
  - type: object
  - required:
     - tag
     - imagePath
    properties:
      imagePath:
        type: string
      tag:
        type: string
      digest:
        type: string
$schema: http://json-schema.org/draft-07/schema#
properties:
  description:
    desc: This is the description for HarnessRegistryDockerConfig
