title: HarnessArtifactRegistryConfig
allOf:
  - $ref: artifact-config.yaml
  - type: object
    required:
      - registryRef
      - type
    properties:
      registryRef:
        type: string
      type:
        type: string
        enum:
         - docker
  - if:
      properties:
        type:
          const: docker
    then:
      properties:
        spec:
          $ref: harness-registry-docker-config.yaml
$schema: http://json-schema.org/draft-07/schema#
properties:
  description:
    desc: This is the description for HarnessArtifactRegistryConfig
