title: HarnessArtifactRegistryConfig
allOf:
  - $ref: artifact-config.yaml
  - type: object
    required:
      - registryRef
      - artifactPath
      - registryType
    properties:
      registryRef:
        type: string
      artifactPath:
        type: string        
      metadata:
        type: string
      repository:
        type: string
      registryType:
        type: string
        enum:
         - docker
  - if:
      properties:
        registryType:
          const: docker
    then:
      properties:
        spec:
          $ref: harness-registry-docker-config.yaml
$schema: http://json-schema.org/draft-07/schema#
properties:
  description:
    desc: This is the description for HarnessArtifactRegistryConfig
