title: JenkinsArtifactConfig
allOf:
- $ref: artifact-config.yaml
- type: object
  required:
  - connectorRef
  - jobName
  properties:
    artifactPath:
      type: string
    build:
      type: string
    connectorRef:
      type: string
    jobName:
      type: string
$schema: http://json-schema.org/draft-07/schema#
properties:
  description:
    desc: This is the description for JenkinsArtifactConfig
