title: MultiDeploymentConfig
type: object
description: Optional configuration for multiple service environment deployment.
properties:
  onFailure:
    $ref: ../../common/strategy-on-failure-type.yaml
  when: 
    type: string
    pattern: ^(?!<\+input>.*\.executionInput\(\)(.*)$)
  maxConcurrency:
    oneOf:
      - type: integer
        format: int32
        minimum: 1
      - type: string
        pattern: ^<\+input>$
        minLength: 1
$schema: http://json-schema.org/draft-07/schema#
