title: MultiDeploymentConfig
type: object
description: Optional configuration for multiple service environment deployment.
properties:
  onFailure:
    $ref: ../../common/strategy-on-failure-type.yaml
$schema: http://json-schema.org/draft-07/schema#
