title: NexusRegistryDockerConfig
allOf:
- $ref: nexus-registry-config-spec.yaml
- type: object
  required:
  - artifactPath
  properties:
    artifactPath:
      type: string
    repositoryPort:
      oneOf:
      - type: string
      - type: integer
    repositoryUrl:
      type: string
- oneOf:
  - required:
    - repositoryPort
  - required:
    - repositoryUrl
$schema: http://json-schema.org/draft-07/schema#
properties:
  description:
    desc: This is the description for NexusRegistryDockerConfig
