title: NexusRegistryRawConfig
allOf:
- $ref: nexus-registry-config-spec.yaml
- type: object
  required:
  - group
  properties:
    group:
      type: string
$schema: http://json-schema.org/draft-07/schema#
properties:
  description:
    desc: This is the description for NexusRegistryRawConfig
