title: SalesforceDxProjectArtifactConfig
allOf:
  - $ref: artifact-config.yaml
  - type: object
    required:
      - metadataStore
      - fetchType
    properties:
      metadataStore:
        $ref: ../../steps/cd/store-config-wrapper.yaml
      fetchType:
        type: string
      metadatas:
        type: array
        items:
          type: string
      sourcePaths:
        type: array
        items:
          type: string
      manifestStore:
        $ref: ../../steps/cd/store-config-wrapper.yaml
$schema: http://json-schema.org/draft-07/schema#
properties:
  description:
    desc: This is the description for SalesforceDxProjectArtifactConfig
