title: SalesforcePackageArtifactConfig
allOf:
  - $ref: artifact-config.yaml
  - type: object
    required:
      - connectorRef
    properties:
      connectorRef:
        type: string
      packageId:
        type: string
      installationKeyRef:
        type: string
      packageVersionId:
        type: string
$schema: http://json-schema.org/draft-07/schema#
properties:
  description:
    desc: This is the description for SalesforcePackageArtifactConfig
