title: SalesforcePackageArtifactConfig
allOf:
  - $ref: salesforce-artifact-config-spec.yaml
  - type: object
  - required:
      - connectorRef
      - packageId
      - versionId
    properties:
      connectorRef:
        type: string
      packageId:
        type: string
      versionId:
        type: string
      installationKeyRef:
        type: string
$schema: http://json-schema.org/draft-07/schema#
properties:
  description:
    desc: This is the description for SalesforcePackageArtifactConfig
