title: SalesforceOrgArtifactConfig
allOf:
  - $ref: salesforce-artifact-config-spec.yaml
  - type: object
  - required:
      - tag
      - imagePath
    properties:
      connectorRef:
        type: string
      metadata:
        $ref: ../../steps/cd/store-config-wrapper.yaml
$schema: http://json-schema.org/draft-07/schema#
properties:
  description:
    desc: This is the description for SalesforceOrgArtifactConfig
