title: SalesforceOrgArtifactConfig
allOf:
  - $ref: artifact-config.yaml
  - type: object
    required:
      - connectorRef
      - fetchType
    properties:
      connectorRef:
        type: string
      fetchType:
        type: string
      metadatas:
        type: array
        items:
          type: string
      sourcePaths:
        type: array
        items:
          type: string
      manifestStore:
        $ref: ../../steps/cd/store-config-wrapper.yaml
$schema: http://json-schema.org/draft-07/schema#
properties:
  description:
    desc: This is the description for SalesforceOrgArtifactConfig
