title: ServiceConfig
type: object
properties:
  service:
    $ref: service-yaml.yaml
  serviceDefinition:
    $ref: service-definition.yaml
  serviceRef:
    type: string
  stageOverrides:
    $ref: stage-overrides-config.yaml
  useFromStage:
    $ref: service-use-from-stage.yaml
  description:
    desc: This is the description for ServiceConfig
$schema: http://json-schema.org/draft-07/schema#
allOf:
- oneOf:
  - required:
    - useFromStage
  - required:
    - service
  - required:
    - serviceRef
- oneOf:
  - required:
    - useFromStage
  - required:
    - serviceDefinition
