title: StageOverridesConfig
type: object
properties:
  artifacts:
    $ref: artifact-list-config.yaml
  configFiles:
    type: array
    items:
      $ref: config-file-wrapper.yaml
  manifests:
    type: array
    items:
      $ref: ../../steps/cd/manifest-config-wrapper.yaml
  variables:
    type: array
    items:
      oneOf:
      - $ref: ../../common/number-ng-variable.yaml
      - $ref: ../../common/secret-ng-variable.yaml
      - $ref: ../../common/string-ng-variable.yaml
  description:
    desc: This is the description for StageOverridesConfig
$schema: http://json-schema.org/draft-07/schema#
