title: StoreConfigWrapperParameters
type: object
properties:
  spec:
    $ref: ../../steps/cd/store-config.yaml
  type:
    type: string
  description:
    desc: This is the description for StoreConfigWrapperParameters
$schema: http://json-schema.org/draft-07/schema#
