title: TanzuApplicationServiceInfrastructure
allOf:
- $ref: infrastructure.yaml
- type: object
  required:
  - connectorRef
  - organization
  - space
  properties:
    connectorRef:
      type: string
    metadata:
      type: string
    organization:
      type: string
    space:
      type: string
$schema: http://json-schema.org/draft-07/schema#
properties:
  description:
    desc: This is the description for TanzuApplicationServiceInfrastructure
