type: object
title: ParallelStageElementNodeConfig
properties:
  stages:
    type: array
    items:
      configRef: ../schema_config.yaml/pipeline_stages
    maxItems: 256
    minItems: 1
$schema: http://json-schema.org/draft-07/schema#
