type: object
title: ParallelStageElementNodeConfig
properties:
  stages:
    type: array
    items:
      "$ref": "./stages.yaml"
    maxItems: 256
    minItems: 1
$schema: http://json-schema.org/draft-07/schema#
