title: AzureWebAppSlotDeploymentStepInfo
allOf:
- $ref: ../../common/step-spec-type.yaml
- type: object
  required:
  - deploymentSlot
  - webApp
  properties:
    delegateSelectors:
      oneOf:
      - type: array
        items:
          type: string
      - type: string
        pattern: ^<\+input>((\.)((executionInput\(\))|(allowedValues|default|regex)\(.+?\)))*$
        minLength: 1
    deploymentSlot:
      type: string
      minLength: 1
    webApp:
      type: string
      minLength: 1
$schema: http://json-schema.org/draft-07/schema#
type: object
required:
- deploymentSlot
- webApp
properties:
  delegateSelectors:
    oneOf:
    - type: array
      items:
        type: string
    - type: string
      pattern: ^<\+input>((\.)((executionInput\(\))|(allowedValues|default|regex)\(.+?\)))*$
      minLength: 1
  deploymentSlot:
    type: string
    minLength: 1
  webApp:
    type: string
    minLength: 1
  description:
    desc: This is the description for AzureWebAppSlotDeploymentStepInfo
