title: ExecutionWrapperConfig
type: object
properties:
  parallel:
    $ref: parallel-step-element-config.yaml
  step:
    oneOf:
    - $ref: ../../common/step-element-config.yaml
    - $ref: ../../steps/custom/custom-approval-step-node.yaml
    - $ref: ../../steps/custom/service-now-approval-step-node.yaml
    - $ref: ../../steps/custom/email-step-node.yaml
    - $ref: ../../steps/custom/jira-update-step-node.yaml
    - $ref: ../../steps/custom/cd-ssca-orchestration-step-node.yaml
    - $ref: ../../steps/custom/jira-create-step-node.yaml
    - $ref: ../../steps/custom/http-step-node.yaml
    - $ref: ../../steps/custom/harness-approval-step-node.yaml
    - $ref: ../../steps/custom/wait-step-node.yaml
    - $ref: ../../steps/custom/jira-approval-step-node.yaml
    - $ref: ../../steps/custom/service-now-create-step-node.yaml
    - $ref: ../../steps/custom/flag-configuration-step-node.yaml
    - $ref: ../../steps/custom/barrier-step-node.yaml
    - $ref: ../../steps/custom/container-step-node.yaml
    - $ref: ../../steps/custom/policy-step-node.yaml
    - $ref: ../../steps/custom/shell-script-step-node.yaml
    - $ref: ../../steps/custom/service-now-update-step-node.yaml
    - $ref: ../../steps/custom/service-now-import-set-step-node.yaml
    - $ref: ../../steps/custom/queue-step-node.yaml
    - $ref: ../../steps/custom/template-step-node.yaml
  stepGroup:
    $ref: step-group-element-config.yaml
  description:
    desc: This is the description for ExecutionWrapperConfig
$schema: http://json-schema.org/draft-07/schema#
