title: StepGroupElementConfig
type: object
required:
- identifier
- name
properties:
  delegateSelectors:
    oneOf:
    - type: array
      items:
        type: string
    - type: string
      pattern: (<\+.+>.*)
      minLength: 1
  failureStrategies:
    oneOf:
    - type: array
      items:
        $ref: ../../common/failure-strategy-config.yaml
    - type: string
      pattern: ^<\+input>$
      minLength: 1
  identifier:
    type: string
    pattern: ^[a-zA-Z_][0-9a-zA-Z_]{0,127}$
  name:
    type: string
    pattern: ^[a-zA-Z_][-0-9a-zA-Z_\s]{0,127}$
  steps:
    type: array
    items:
      $ref: execution-wrapper-config.yaml
    maxItems: 2147483647
    minItems: 1
  strategy:
    oneOf:
    - $ref: ../../common/strategy-config.yaml
    - type: string
      pattern: ^<\+input>$
      minLength: 1
  template:
    $ref: ../../steps/custom/template-link-config.yaml
  when:
    oneOf:
    - $ref: ../../common/step-when-condition.yaml
    - type: string
      pattern: ^<\+input>$
      minLength: 1
  description:
    desc: This is the description for StepGroupElementConfig
$schema: http://json-schema.org/draft-07/schema#
allOf:
- oneOf:
  - required:
    - template
  - required:
    - steps
