title: HarnessForConfig
type: object
properties:
  end:
    oneOf:
    - type: integer
      format: int32
      minimum: 0
    - type: string
      pattern: (<\+.+>.*)
      minLength: 1
  items:
    oneOf:
    - type: array
      items:
        type: string
    - type: string
      pattern: (<\+.+>.*)
      minLength: 1
  maxConcurrency:
    oneOf:
    - type: integer
      format: int32
      minimum: 0
    - type: string
      pattern: (<\+.+>.*)
      minLength: 1
  partitionSize:
    oneOf:
    - type: integer
      format: int32
      minimum: 0
    - type: string
      pattern: (<\+.+>.*)
      minLength: 1
  start:
    oneOf:
    - type: integer
      format: int32
      minimum: 0
    - type: string
      pattern: (<\+.+>.*)
      minLength: 1
  times:
    oneOf:
    - type: integer
      format: int32
      minimum: 0
    - type: string
      pattern: (<\+.+>.*)
      minLength: 1
  unit:
    type: string
    enum:
    - Percentage
    - Count
  description:
    desc: This is the description for HarnessForConfig
$schema: http://json-schema.org/draft-07/schema#
allOf:
- oneOf:
  - required:
    - times
  - required:
    - items
