pipeline:
  name: test
  identifier: test
  description: description
  projectIdentifier: hotstar
  orgIdentifier: a_org
  tags: {}
  stages:
    - stage:
        name: test
        identifier: test
        description: <+inputs.input-1>
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: JiraCreate
                  name: JiraCreate_1
                  identifier: JiraCreate_1
                  spec:
                    connectorRef: account.Test_jira
                    projectKey: dummy-project
                    issueType: dummy-issue
                    fields: []
                  timeout: 10m
        tags: {}
# For the following inputs, we haven't provided a value so, it's value will be asked during the runtime.
#  Default value for input-1 is abc and for input-2, it is 1, so, if user doesn't provide a value during runtime,
#  input-1 will be set as abc and input-2 will be set as 1.
# Also, there's a validation that value should of input-1 should be one of a, b, abc
#  for input-2, it should be a single digit number from 1 to 9
  inputs:
    input-1:
      type: string
      default: abc
      validator:
        allowed_values:
          - a
          - b
          - abc
    input-2:
      type: number
      default: 1
      validator:
        regex: [1-9]