type: object
title: pipeline
required:
  - spec
  - version
  - kind
properties:
  version:
    description: Version defines the schema version.
    type: number
    enum:
      - 1
  kind:
    description: defines the kind of yaml (pipeline/template/trigger)
    type: string
    enum:
      - pipeline
  type:
    description: defines the type of yaml (add only when pipeline uses a template)
    type: string
    enum:
      - template

if:
  properties:
    type:
      const: template
  required:
    - type
then:
  properties:
    spec:
      $ref: ./template-link-config-spec.yaml
else:
  properties:
    spec:
      $ref: ./pipeline_spec.yaml
"$schema": http://json-schema.org/draft-07/schema#
