type: object
title: pipeline
required:
  - spec
  - version
  - kind
properties:
  version:
    description: Version defines the schema version.
    type:
      - number
  kind:
    description: defines the kind of yaml (pipeline/template)
    type: string
    enum:
      - pipeline
  type:
    description: defines the type of yaml (add only when pipeline uses a template)
    type: string
    enum:
      - template

allOf:
  - if:
      properties:
        type:
          const: template
    then:
      $ref: ./pipeline_using_template_spec.yaml
  - if:
      not:
        required:
          - type
    then:
      $ref: ./pipeline_spec.yaml
"$schema": http://json-schema.org/draft-07/schema#
