type: object
title: pipeline
properties:
  required:
    - stages
    - version
  version:
    - type: number
  stages:
    type: array
    items:
      "$ref": "./stages/stages.yaml"
    maxItems: 2147483647
    minItems: 1
  variables:
    type: array
    items:
      oneOf:
        - "$ref": "./common/number-ng-variable.yaml"
        - "$ref": "./common/string-ng-variable.yaml"
        - "$ref": "./common/secret-ng-variable.yaml"
"$schema": http://json-schema.org/draft-07/schema#
