#!/bin/bash

#source_dir="../pipeline/stages/security/"
#destination_dir="../pipeline/steps/common/"

#file_list2=(
#    "brakeman-scan-node.yaml"
#    "mend-scan-node.yaml"
#    "fortify-on-demand-scan-node.yaml"
#    "jfrog-xray-scan-node.yaml"
#    "grype-scan-node.yaml"
#    "black-duck-scan-node.yaml"
#    "openvas-scan-node.yaml"
#    "owasp-scan-node.yaml"
#    "aqua-trivy-scan-node.yaml"
#    "nmap-scan-node.yaml"
#    "nessus-scan-node.yaml"
#    "data-theorem-scan-node.yaml"
#    "docker-content-trust-scan-node.yaml"
#    "security-node.yaml"
#    "reapsaw-scan-node.yaml"
#    "sysdig-scan-node.yaml"
#    "sniper-scan-node.yaml"
#    "burp-scan-node.yaml"
#    "qualys-scan-node.yaml"
#    "sonarqube-scan-node.yaml"
#    "zap-scan-node.yaml"
#    "aws-ecr-scan-node.yaml"
#    "veracode-scan-node.yaml"
#    "tenable-scan-node.yaml"
#    "nikto-scan-node.yaml"
#    "bandit-scan-node.yaml"
#    "checkmarx-scan-node.yaml"
#    "clair-scan-node.yaml"
#    "prisma-cloud-scan-node.yaml"
#    "shift-left-scan-node.yaml"
#    "metasploit-scan-node.yaml"
#    "prowler-scan-node.yaml"
#    "nexus-iqscan-node.yaml"
#)
#
#file_list3=(
#    "mend-step-info.yaml"
#    "fortify-on-demand-step-info.yaml"
#    "jfrog-xray-step-info.yaml"
#    "aqua-trivy-step-info.yaml"
#    "nmap-step-info.yaml"
#    "nessus-step-info.yaml"
#    "data-theorem-step-info.yaml"
#    "docker-content-trust-step-info.yaml"
#    "aws-ecr-step-info.yaml"
#    "bandit-step-info.yaml"
#    "black-duck-step-info.yaml"
#    "brakeman-step-info.yaml"
#    "burp-step-info.yaml"
#    "checkmarx-step-info.yaml"
#    "grype-step-info.yaml"
#    "metasploit-step-info.yaml"
#    "nexus-iqstep-info.yaml"
#    "nikto-step-info.yaml"
#    "openvas-step-info.yaml"
#    "owasp-step-info.yaml"
#    "prisma-cloud-step-info.yaml"
#    "prowler-step-info.yaml"
#    "qualys-step-info.yaml"
#    "reapsaw-step-info.yaml"
#    "security-step-info.yaml"
#    "shift-left-step-info.yaml"
#    "sniper-step-info.yaml"
#    "snyk-step-info.yaml"
#    "sonarqube-step-info.yaml"
#    "sysdig-step-info.yaml"
#    "tenable-step-info.yaml"
#    "veracode-step-info.yaml"
#    "zap-step-info.yaml"
#    "upload-to-artifactory-step-info.yaml"
#    "upload-to-gcsstep-info.yaml"
#    "upload-to-s3-step-info.yaml"
#    "ecrstep-info.yaml"
#    "save-cache-gcsstep-info.yaml"
#    "gcrstep-info.yaml"
#)

stofile=(
    "stoyaml-image.yaml"
    "stoyaml-blackduck-tool-data.yaml"
    "stoyaml-checkmarx-tool-data.yaml"
    "stoyaml-fodtool-data.yaml"
    "stoyaml-mend-tool-data.yaml"
    "stoyaml-veracode-tool-data.yaml"
    "stoyaml-zap-tool-data.yaml"
    "stoyaml-wiz-tool-data.yaml"
)

file_list=(
  "prisma-cloud-scan-node.yaml"
  "docker-content-trust-scan-node.yaml"
  "owasp-scan-node.yaml"
  "bandit-scan-node.yaml"
  "grype-scan-node.yaml"
  "prowler-scan-node.yaml"
  "mend-scan-node.yaml"
  "qualys-scan-node.yaml"
  "nessus-scan-node.yaml"
  "zap-scan-node.yaml"
  "openvas-scan-node.yaml"
  "osv-scanner-scan-node.yaml"
  "aws-ecr-scan-node.yaml"
  "burp-scan-node.yaml"
  "checkmarx-scan-node.yaml"
  "metasploit-scan-node.yaml"
  "reapsaw-scan-node.yaml"
  "black-duck-scan-node.yaml"
  "shift-left-scan-node.yaml"
  "tenable-scan-node.yaml"
  "jfrog-xray-scan-node.yaml"
  "nexus-iqscan-node.yaml"
  "sniper-scan-node.yaml"
  "clair-scan-node.yaml"
  "sysdig-scan-node.yaml"
  "security-node.yaml"
  "sonarqube-scan-node.yaml"
  "nikto-scan-node.yaml"
  "brakeman-scan-node.yaml"
  "data-theorem-scan-node.yaml"
  "aqua-trivy-scan-node.yaml"
  "fortify-on-demand-scan-node.yaml"
  "veracode-scan-node.yaml"
  "nmap-scan-node.yaml"
  "wiz-scan-node.yaml"
  )

newFileInfoList=(
  "prisma-cloud-step-info.yaml"
  "docker-content-trust-step-info.yaml"
  "owasp-step-info.yaml"
  "bandit-step-info.yaml"
  "grype-step-info.yaml"
  "prowler-step-info.yaml"
  "mend-step-info.yaml"
  "qualys-step-info.yaml"
  "nessus-step-info.yaml"
  "zap-step-info.yaml"
  "openvas-step-info.yaml"
  "aws-ecr-step-info.yaml"
  "burp-step-info.yaml"
  "checkmarx-step-info.yaml"
  "checkov-step-info.yaml"
  "metasploit-step-info.yaml"
  "reapsaw-step-info.yaml"
  "black-duck-step-info.yaml"
  "shift-left-step-info.yaml"
  "tenable-step-info.yaml"
  "jfrog-xray-step-info.yaml"
  "nexus-iqstep-info.yaml"
  "sniper-step-info.yaml"
  "sysdig-step-info.yaml"
  "sonarqube-step-info.yaml"
  "aqua-trivy-step-info.yaml"
  "brakeman-step-info.yaml"
  "data-theorem-step-info.yaml"
  "fortify-on-demand-step-info.yaml"
  "nikto-step-info.yaml"
  "nmap-step-info.yaml"
  "security-step-info.yaml"
  "snyk-step-info.yaml"
  "veracode-step-info.yaml"
  "wiz-step-info.yaml"
)



# Move selected files to the destination directory
#for file_name in "${stofile[@]}"; do
#    source_path="${source_dir}${file_name}"
#    destination_path="${destination_dir}${file_name}"
#    mv "$source_path" "$destination_path"
#done

#echo "Files moved successfully!"


destination_dir="../pipeline/steps/ci/"
# Loop through the file_list and delete each file
for file in "${stofile[@]}"; do
    rm "${destination_dir}${file}"
done

echo "All files have been deleted."
