type: object
title: TemplateLinkConfigSpec
required:
  - ref
properties:
  ref:
    type: string
    description: ref of the template to be linked in the pipeline, format - id@version
    example: my_template@v1.0
    pattern: "^[a-zA-Z_][0-9a-zA-Z_]{0,127}@[0-9a-zA-Z][^\\s/&]{0,127}$"
  inputs:
    type: object
    description: inputs to be used in the linked template
    additionalProperties:
      anyOf:
        - string
        - array
        - number
        - object
        - boolean
    propertyNames:
      pattern: "^[a-zA-Z_][0-9a-zA-Z_\\.$-]{0,127}$"

