title: HttpHeaderConfig
type: object
properties:
  key:
    type: string
  value:
    type: string
  description:
    desc: This is the description for HttpHeaderConfig
$schema: http://json-schema.org/draft-07/schema#
