title: KeyValuesImportDataSpec
allOf:
- $ref: import-data-spec.yaml
- type: object
  required:
  - fields
  properties:
    fields:
      type: array
      items:
        $ref: service-now-field.yaml
$schema: http://json-schema.org/draft-07/schema#
properties:
  description:
    desc: This is the description for KeyValuesImportDataSpec
