title: ParameterFieldMatrixConfigInterface
type: object
properties:
  defaultValue:
    $ref: matrix-config-interface.yaml
  executionInput:
    type: boolean
  expression:
    type: boolean
  expressionValue:
    type: string
  inputSetValidator:
    $ref: input-set-validator.yaml
  jsonResponseField:
    type: boolean
  responseField:
    type: string
  typeString:
    type: boolean
  value:
    $ref: matrix-config-interface.yaml
$schema: http://json-schema.org/draft-07/schema#
