title: PolicyConfig
type: object
required:
- policySets
properties:
  policySets:
    oneOf:
    - type: array
      items:
        type: string
    - type: string
      pattern: ^<\+input>((\.)((executionInput\(\))|(allowedValues|default|regex)\(.+?\)))*$
      minLength: 1
$schema: http://json-schema.org/draft-07/schema#
