title: TemplateLinkConfig
type: object
required:
- templateRef
properties:
  templateInputs:
    $ref: json-node.yaml
  templateRef:
    type: string
  templateVariables:
    $ref: json-node.yaml
  versionLabel:
    type: string
    pattern: ^[0-9a-zA-Z][^\s]{0,63}$
$schema: http://json-schema.org/draft-07/schema#
