title: AIAgentMLOpsOnFailureConfig
type: object
required:
  - action
  - errors
properties:
  action:
    $ref: aiagentmlops-failure-strategy-action-config.yaml
  errors:
    type: array
    items:
      type: string
      enum:
        - Unknown
        - AllErrors
        - Authentication
        - Connectivity
        - Timeout
        - Authorization
        - Verification
        - DelegateProvisioning
        - PolicyEvaluationFailure
        - InputTimeoutError
        - ApprovalRejection
        - DelegateRestart
        - UserMarkedFailure
  description:
    desc: This is the description for OnFailureConfig
$schema: http://json-schema.org/draft-07/schema#
