title: AIAgentMLOpsFailureStrategyActionConfig
type: object
required:
  - type
discriminator: type
properties:
  type:
    type: string
    enum:
      - Ignore
      - MarkAsSuccess
      - Abort
      - Retry
  description:
    desc: This is the description for FailureStrategyActionConfig
$schema: http://json-schema.org/draft-07/schema#
