title: DBDevOpsFailureStrategyConfig
type: object
required:
  - onFailure
properties:
  onFailure:
    $ref: db-devops-on-failure-config.yaml
  description:
    desc: This is the description for FailureStrategyConfig
metadata:
  inputProperties:
    type: string
    internalType: failure_strategy
$schema: http://json-schema.org/draft-07/schema#
