title: FailureStrategyConfig
type: object
required:
- onFailure
properties:
  onFailure:
    $ref: on-failure-config.yaml
  description:
    desc: This is the description for FailureStrategyConfig
$schema: http://json-schema.org/draft-07/schema#
