title: FailureStrategyActionConfig
type: object
required:
- type
oneOf:
  - $ref: ignore-failure-action-config.yaml
  - $ref: retry-failure-action-config.yaml
  - $ref: mark-as-success-failure-action-config.yaml
  - $ref: abort-failure-action-config.yaml
  - $ref: stage-rollback-failure-action-config.yaml
  - $ref: step-group-rollback-failure-action-config.yaml
  - $ref: pipeline-rollback-failure-action-config.yaml
  - $ref: manual-intervention-failure-action-config.yaml
  - $ref: proceed-with-default-values-failure-action-config.yaml
  - $ref: mark-as-failure-action-config.yaml
  - $ref: retry-step-group-failure-action-config.yaml
properties:
  type:
    type: string
    enum:
    - Ignore
    - Retry
    - MarkAsSuccess
    - Abort
    - StageRollback
    - StepGroupRollback
    - PipelineRollback
    - ManualIntervention
    - ProceedWithDefaultValues
    - MarkAsFailure
    - RetryStepGroup
  description:
    desc: This is the description for FailureStrategyActionConfig
$schema: http://json-schema.org/draft-07/schema#
