title: PolicyConfig
type: object
required:
- policySets
properties:
  policySets:
    oneOf:
    - type: array
      items:
        type: string
    - type: string
      pattern: ^<\+input>((\.)((executionInput\(\))|(allowedValues|selectOneFrom|default|regex)\(.+?\)))*$
      minLength: 1
  description:
    desc: This is the description for PolicyConfig
metadata:
  inputProperties:
    type: object
    internalType: policy_config
$schema: http://json-schema.org/draft-07/schema#
