title: RetryStepGroupFailureActionConfig
type: object
properties:
  type:
    type: string
    enum:
      - RetryStepGroup
  spec:
    properties:
      retryCount:
        description: "Number of retries to attempt"
      retryIntervals:
        description: "List of interval durations between retries"
$schema: http://json-schema.org/draft-07/schema#
