title: RetryFailureSpecConfig
type: object
properties:
  condition:
    type: string
    description: "Expression that evaluates to determine if retry should be performed, e.g. '<+step.exitCode> == 137'"
  retryCount:
    type: integer
    minimum: 1
  retryIntervals:
    type: array
    minItems: 1
    items:
      type: string
      pattern: "^[0-9]+(s|m|h|d)$"
      description: "Duration string e.g. '10s', '1m', '2h'"
  onRetryFailure:
    type: object
    properties:
      action:
        type: object
        description: "Action to take. Recommended types: Abort, Ignore, MarkAsSuccess, MarkAsFailure"
$schema: http://json-schema.org/draft-07/schema#
