title: RetryStepGroupFailureActionConfig
type: object
properties:
  type:
    type: string
    enum:
      - RetryStepGroup
  spec:
    type: object
    properties:
      condition:
        type: object
        properties:
          value:
            type: string
            description: "Expression that evaluates to determine if retry should be performed, e.g. '<+step.exitCode> == 137'"
          expression:
            type: object
      retryCount:
        type: object
        properties:
          value:
            type: integer
            minimum: 1
            description: "Number of retries to attempt"
      retryIntervals:
        type: object
        properties:
          value:
            type: array
            items:
              type: string
              pattern: "^[0-9]+(s|m|h|d)$"
              description: "Duration string e.g. '10s', '1m', '2h'"
            description: "List of interval durations between retries"
      onRetryFailure:
        type: object
        properties:
          action:
            type: object
            description: "Action to take. Recommended types: Abort, Ignore, MarkAsSuccess, MarkAsFailure"
$schema: http://json-schema.org/draft-07/schema#
