title: RetryFailureActionConfig
type: object
properties:
  type:
    type: string
    enum:
      - Retry
  spec:
    $ref: retry-failure-spec-config.yaml
  description:
    desc: This is the description for RetryFailureActionConfig
$schema: http://json-schema.org/draft-07/schema#
