title: RetryFailureSpecConfig
type: object
properties:
  condition:
    description: "Expression that evaluates to determine if retry should be performed, e.g. '<+step.exitCode> == 137'"
  retryCount:
    description: "Number of retries to attempt"
  retryIntervals:
    description: "List of interval durations between retries"
  onRetryFailure:
    properties:
      action:
        description: "Action to take. Recommended types: Abort, Ignore, MarkAsSuccess, MarkAsFailure"
$schema: http://json-schema.org/draft-07/schema#
