title: RetryFailureSpecConfig
type: object
properties:
  retryCount:
    type: integer
    minimum: 1
  retryIntervals:
    type: array
    minItems: 1
    items:
      type: string
      pattern: "^[0-9]+(s|m|h|d)$"
      description: "Duration string e.g. '10s', '1m', '2h'"
  onRetryFailure:
    type: object
    properties:
      action:
        oneOf:
          - $ref: abort-failure-action-config.yaml
          - $ref: ignore-failure-action-config.yaml
          - $ref: mark-as-success-failure-action-config.yaml
          - $ref: mark-as-failure-action-config.yaml
          - $ref: manual-intervention-failure-action-config.yaml
  condition:
    type: string
    description: "Expression that evaluates to determine if retry should be performed, e.g. '<+step.exitCode> == 137'"
$schema: http://json-schema.org/draft-07/schema#
