title: RunModeConfig
type: object
required:
- type
properties:
  type:
    type: string
    enum:
    - Manual
    - Auto
$schema: http://json-schema.org/draft-07/schema#
allOf:
- if:
    properties:
      type:
        const: Manual
  then:
    required:
    - timeout
    properties:
      timeout:
        type: string
        pattern: ^(([1-9])+\d+[s])|(((([1-9])+\d*[mhwd])+([\s]?\d+[smhwd])*)|(.*<\+.*>(?!.*\.executionInput\(\)).*)|(^$))$
- if:
    properties:
      type:
        const: Auto
  then:
    properties: {}
