title: StrategyConfig
type: object
properties:
  when:
    type: string
    pattern: ^(?!<\+input>.*\.executionInput\(\)(.*)$)
  matrix:
    oneOf:
    - $ref: parameter-field-matrix-config-interface.yaml
    - type: string
      pattern: ^<\+input>((\.)((executionInput\(\))|(allowedValues|default|regex)\(.+?\)))*$
      minLength: 1
  parallelism:
    oneOf:
    - type: integer
      format: int32
      minimum: 0
    - type: string
      pattern: (<\+.+>.*)
      minLength: 1
  repeat:
    $ref: harness-for-config.yaml
  onFailure:
    $ref: strategy-on-failure-type.yaml
  description:
    desc: This is the description for StrategyConfig
metadata:
  inputProperties:
    type: object
    internalType: strategy_config
$schema: http://json-schema.org/draft-07/schema#
allOf:
- oneOf:
  - required:
    - repeat
  - required:
    - parallelism
  - required:
    - matrix
