version: 1
kind: pipeline
spec:
  stages:
    - name: test
      id: test
      desc: <+inputs.get("input-1")>
      type: custom
      spec:
        steps:
          - type: jira-create
            name: JiraCreate_1
            id: JiraCreate_1
            spec:
              connector: account.Test_jira
              project: dummy-project
              issue: dummy-issue
              fields: []
            timeout: 10m
      labels: {}
  inputs:
    input-1:
      type: string
  timeout: 10m