version: 1
kind: pipeline
spec:
  stages:
    - name: test
      id: test
      desc: <+inputs.input-1>
      type: custom
      spec:
        steps:
          - type: jira-create
            name: JiraCreate_1
            id: JiraCreate_1
            spec:
              connectorRef: account.Test_jira
              projectKey: dummy-project
              issueType: dummy-issue
              fields: []
            timeout: 10m
      tags: {}
  inputs:
    input-1:
      type: string