title: TemplateLinkConfig
type: object
required:
- templateRef
properties:
  templateInputs:
    $ref: ../../common/json-node.yaml
  templateRef:
    type: string
  templateVariables:
    $ref: ../../common/json-node.yaml
  versionLabel:
    type: string
    pattern: ^[0-9a-zA-Z][^\s]{0,63}$
  description:
    desc: This is the description for TemplateLinkConfig
$schema: http://json-schema.org/draft-07/schema#
