steps: 
  - ../../common/step-element-config.yaml
  - ../../steps/custom/barrier-step-node.yaml
  - ../../steps/custom/wait-step-node.yaml
  - ../../steps/custom/service-now-approval-step-node.yaml
  - ../../stages/template/template-stage-node.yaml
  - ../../steps/custom/harness-approval-step-node.yaml
  - ../../steps/custom/service-now-update-step-node.yaml
  - ../../steps/custom/http-step-node.yaml
  - ../../steps/custom/flag-configuration-step-node.yaml
  - ../../steps/custom/email-step-node.yaml
  - ../../steps/custom/queue-step-node.yaml
  - ../../steps/custom/service-now-create-step-node.yaml
  - ../../steps/custom/shell-script-step-node.yaml
  - ../../steps/custom/cd-ssca-enforcement-step-node.yaml
  - ../../steps/custom/jira-create-step-node.yaml
  - ../../steps/custom/cd-ssca-orchestration-step-node.yaml
  - ../../steps/custom/jira-update-step-node.yaml
  - ../../steps/custom/container-step-node.yaml
  - ../../steps/custom/jira-approval-step-node.yaml
  - ../../steps/custom/custom-approval-step-node.yaml
  - ../../steps/custom/service-now-import-set-step-node.yaml
  - ../../steps/custom/policy-step-node.yaml
  - ../../steps/common/dbops-apply-schema-step-node.yaml
  - ../../steps/common/dbops-rollback-schema-step-node.yaml