title: ApprovalStageConfig
type: object
required:
  - steps
properties:
  steps:
    type: array
    items:
      configRef: ./approval-stage-wrapper-config.yaml/steps
    maxItems: 256
    minItems: 1
$schema: http://json-schema.org/draft-07/schema#
