type: object
title: pipeline
properties:
  allowStageExecutions:
    type: boolean
  fixedInputsOnRerun:
    type: boolean
  delegateSelectors:
    oneOf:
      - type: array
        items:
          type: string
      - type: string
        pattern: "(<\\+.+>.*)"
        minLength: 1
  description:
    type: string
  flowControl:
    "$ref": "./flow_control.yaml"
  identifier:
    type: string
    pattern: "^[a-zA-Z_][0-9a-zA-Z_]{0,127}$"
  name:
    type: string
    pattern: "^[a-zA-Z_0-9-.][-0-9a-zA-Z_\\s.]{0,127}$"
  notificationRules:
    type: array
    items:
      "$ref": "./notification-rules.yaml"
  orgIdentifier:
    type: string
  projectIdentifier:
    type: string
  properties:
    type: object
    properties:
      ci:
        type: object
        properties:
          codebase:
            $ref: "./codebase.yaml"
  stages:
    type: array
    items:
      "$ref": "./stages/stages.yaml"
    maxItems: 2147483647
    minItems: 1
  tags:
    type: object
    additionalProperties:
      type: string
  template:
    "$ref": "./steps/custom/template-link-config.yaml"
  timeout:
    type: string
    pattern: "^(([1-9])+\\d+[s])|(((([1-9])+\\d*[mhwd])+([\\s]?\\d+[smhwd])*)|(<\\+input>.*)|(.*<\\+.*>.*)|(^$))$"
  variables:
    type: array
    items:
      oneOf:
        - "$ref": "./common/number-ng-variable.yaml"
        - "$ref": "./common/string-ng-variable.yaml"
        - "$ref": "./common/secret-ng-variable.yaml"
"$schema": http://json-schema.org/draft-07/schema#
