type: object
title: templateSpec
required:
  - templateRef
properties:
  templateInputs:
    type: object
  templateRef:
    type: string
  templateVariables:
    type: object
  versionLabel:
    type: string
    pattern: "^[0-9a-zA-Z][^\\s]{0,63}$"
"$schema": http://json-schema.org/draft-07/schema#
