version: 1
kind: pipeline
spec:
  stages:
    - type: template
      ref: nested@v1
      spec:
        name: cstpl
        inputs:
          env: abc
    - type: custom
      when: <+ stages.nested.outputs.status> == 200
      spec:
        steps:
          - type: plugin
            spec:
              uses: http
              with:
                url: <+ stages.nested.outputs.url>
