version: 1
stages:
  - type: template
    id: nested
    versionLabel: v1
    spec:
      name: cstpl
      inputs:
        env: abc
  - type: custom
    when: <+ stages.nested.outputs.status> == 200
    spec:
      steps:
        - type: plugin
          spec:
            uses: http
            with:
              url: <+ stages.nested.outputs.url>
