version: 1
kind: pipeline
spec:
  stages:
    - type: custom
      spec:
        steps:
          - type: http
            spec:
              url: <+ stages.nested.outputs.url>
              method: GET
  timeout: 10m
