title: pipeline
type: object
properties:
  id:
    type: string
    description: "Unique pipeline identifier"
  name:
    type: string
    description: "Pipeline name"
  inputs:
    type: object
    description: "Pipeline input variables"
    additionalProperties:
      $ref: "./common/input.yaml"
  delegate:
    oneOf:
      - type: string
      - type: array
        items:
          type: string
    description: "Default delegate for all stages"
  env:
    type: object
    additionalProperties:
      type: string
    description: "Global environment variables"
  service:
    $ref: "./common/service.yaml"
  environment:
    $ref: "./common/environment.yaml"
  stages:
    type: array
    items:
      $ref: "./stage.yaml"
    minItems: 1
    description: "Pipeline stages"
  repo:
    $ref: "./common/repository.yaml"
  clone:
    $ref: "./common/clone.yaml"
  status:
    $ref: "./common/status.yaml"
  barriers:
    type: array
    items:
      type: string
    description: "Pipeline barriers"
  if:
    type: string
    description: "Conditional pipeline execution"
  on:
    $ref: "./common/on.yaml"
  timeout:
    type: string
    pattern: "^(([1-9])+\\d+[s])|(((([1-9])+\\d*[mhwd])+([\\s]?\\d+[smhwd])*)|(<\\+input>.*)|(.*<\\+.*>.*)|(^$))$"
    description: "Pipeline timeout duration"
  # GitHub compatibility
  jobs:
    type: object
    additionalProperties:
      $ref: "./stage.yaml"
    description: "GitHub Actions compatible jobs syntax"
  concurrency:
    $ref: "./common/concurrency.yaml"
  default:
    type: object
    description: "Default settings"
  permissions:
    $ref: "./common/permissions.yaml"
"$schema": http://json-schema.org/draft-07/schema#
