steps:
  - ../../steps/ci/step_action_node.yaml
  - ../../steps/ci/step_background_node.yaml
  - ../../steps/ci/step_bitrise_node.yaml
  - ../../steps/ci/step_ti_node.yaml
  - ../../steps/ci/step_plugin_node.yaml
  - ../../steps/ci/parallel-node.yaml
  - ../../steps/ci/step-group-node.yaml
  - ../../steps/common/step_run_node.yaml
  - ../../steps/common/template-step-node.yaml
