title: CIStageSpecElementConfig
type: object
required:
- steps
properties:
  rollbackSteps:
    type: array
    items:
      configRef: ./ci-stage-spec-element-wrapper-config.yaml/steps
  steps:
    type: array
    items:
      configRef: ./ci-stage-spec-element-wrapper-config.yaml/steps
    maxItems: 256
    minItems: 1
  cache:
    $ref: ./caching.yaml
    description: Configures the cache behavior.
  clone:
    $ref: ./clone_stage.yaml
    description: Overrides the clone behavior.
  platform:
    $ref: ./platform.yaml
    description: Configures the target execution platform.
  runtime:
    $ref: ./runtime.yaml
    description: Configures the target runtime engine.
  envs:
    type: object
    additionalProperties:
      type: string
    description: The stage environment variables.
  volumes:
    description: Configures a container volumes.
    items:
      $ref: ./volume.yaml
    type: array
$schema: http://json-schema.org/draft-07/schema#
