steps:
  - ../../steps/ci/step_action.yaml
  - ../../steps/ci/step_background.yaml
  - ../../steps/ci/step_bitrise.yaml
  - ../../steps/ci/step_ti.yaml
  - ../../steps/ci/step_plugin.yaml
  - ../../steps/ci/parallel-node.yaml
  - ../../steps/ci/step-group-node.yaml
  - ../../steps/common/step_run.yaml
  - ../../steps/common/template-step-node.yaml
