title: IntegrationStageConfigImpl
type: object
properties:
  cache:
    $ref: ./caching.yaml
    description: Configures the cache behavior.
  clone:
    $ref: ./clone_stage.yaml
    description: Overrides the clone behavior.
  # clone:
  #   $ref: ./clone.yaml
  #   description: Configures the default clone behavior.
  # repository:
  #   $ref: ./repository.yaml
  #   description: Configures the remote repository.

  platform:
    $ref: ./platform.yaml
    description: Configures the target execution platform.
  runtime:
    $ref: ./runtime.yaml
    description: Configures the target runtime engine.
  steps:
    description: Configures a series of steps to executes.
    items:
      $ref: ../../steps/step.yaml
    type: array
  envs:
    type: object
    additionalProperties:
      type: string
    description: The stage environment variables.
  volumes:
    description: Configures a container volumes.
    items:
      $ref: ./volume.yaml
    type: array

