title: DockerHubArtifactConfig
allOf:
- $ref: basic-artifact-store-config.yaml
- type: object
  required:
  - connector
  - location
  properties:
    connector:
      type: string
    location:
      type: string
$schema: http://json-schema.org/draft-07/schema#
