title: DockerHubArtifactConfig
allOf:
- $ref: basic-artifact-store-config.yaml
- type: object
  required:
  - connector
  - location
  properties:
    connector:
      type: string
    location:
      type: string
      description: this is reference to artifact image in following format /library/nginx:alpine
$schema: http://json-schema.org/draft-07/schema#
