title: GithubStoreConfig
allOf:
- $ref: basic-manifest-store-config.yaml
- type: object
  required:
  - connector
  - location
  properties:
    location:
      type: string
    connector:
      type: string
    repo:
      type: string
$schema: http://json-schema.org/draft-07/schema#

