title: FeatureFlagStageConfig
type: object
properties:
  execution:
    $ref: execution-element-config.yaml
  description:
    desc: This is the description for FeatureFlagStageConfig
$schema: http://json-schema.org/draft-07/schema#
