title: ConfigFile
type: object
required:
- id
- type
- spec
properties:
  id:
    type: string
  type:
    type: string
    enum:
    - harness
allOf:
- if:
    properties:
      type:
        const: harness
        spec:
          $ref: ./stores/harness-store.yaml
$schema: http://json-schema.org/draft-07/schema#