title: ValuesManifest
allOf:
- $ref: basic-manifest-config.yaml
- type: object
  required:
  - spec
  - type
  properties:
    type:
      type: string
      enum:
      - github
    spec:
      type: object
      allOf:
      - if:
          properties:
            type:
              const: github
        then:
          properties:
            spec:
              $ref: ./stores/github-store-config.yaml
$schema: http://json-schema.org/draft-07/schema#