title: EnvironmentItems
description: List of environments for multi-environment deployment, or an expression.
oneOf:
  - type: array
    items:
      $ref: ./environment-item.yaml
  - $ref: ../../common/expression.yaml
$schema: http://json-schema.org/draft-07/schema#
