title: EnvironmentGroup
description: Environment group configuration.
type: object
required:
  - id
properties:
  id:
    description: Environment group identifier.
    type: string
  parallel:
    description: Execute environments in parallel (all at once). Defaults to false, so environments run one at a time (serially) unless set to true.
    oneOf:
      - type: boolean
        default: false
      - $ref: ../../common/expression.yaml
  items:
    description: List of environments from the group.
    $ref: ./environment-items.yaml
  filters:
    description: Filters for selecting environments and infrastructures.
    $ref: ./filters.yaml
additionalProperties: false
$schema: http://json-schema.org/draft-07/schema#
