title: AgentApplicationTargets
type: object
required:
- agentId
- applicationName
properties:
  agentId:
    type: string
  applicationName:
    type: string
  description:
    desc: This is the description for AgentApplicationTargets
$schema: http://json-schema.org/draft-07/schema#
