title: CloudformationDeleteStackStepConfiguration
type: object
required:
- spec
- type
properties:
  type:
    type: string
  description:
    desc: This is the description for CloudformationDeleteStackStepConfiguration
$schema: http://json-schema.org/draft-07/schema#
allOf:
- if:
    properties:
      type:
        const: Inherited
  then:
    properties:
      spec:
        $ref: inherited-cloudformation-delete-stack-step-configuration.yaml
- if:
    properties:
      type:
        const: Inline
  then:
    properties:
      spec:
        $ref: inline-cloudformation-delete-stack-step-configuration.yaml
