title: CreatePRStepUpdateConfigScriptBaseSource
type: object
discriminator: type
properties:
  type:
    type: string
  description:
    desc: This is the description for CreatePRStepUpdateConfigScriptBaseSource
$schema: http://json-schema.org/draft-07/schema#
