title: CreatePRStepUpdateConfigScriptInlineSource
allOf:
- $ref: create-prstep-update-config-script-base-source.yaml
- type: object
  properties:
    updateConfigScript:
      type: string
$schema: http://json-schema.org/draft-07/schema#
properties:
  description:
    desc: This is the description for CreatePRStepUpdateConfigScriptInlineSource
