title: InlineTerraformBackendConfigSpec
allOf:
- $ref: terraform-backend-config-spec.yaml
- type: object
  properties:
    content:
      type: string
$schema: http://json-schema.org/draft-07/schema#
properties:
  description:
    desc: This is the description for InlineTerraformBackendConfigSpec
