title: OciHelmChartStoreGenericConfig
allOf:
- $ref: oci-helm-chart-store-config.yaml
- type: object
  properties:
    connectorRef:
      oneOf:
      - $ref: parameter-field-string.yaml
      - type: string
    metadata:
      type: string
$schema: http://json-schema.org/draft-07/schema#
properties:
  description:
    desc: This is the description for OciHelmChartStoreGenericConfig
