title: S3UrlStoreConfig
allOf:
- $ref: store-config.yaml
- type: object
  required:
  - connectorRef
  - region
  - urls
  properties:
    connectorRef:
      type: string
    metadata:
      type: string
    region:
      type: string
    urls:
      oneOf:
      - type: array
        items:
          type: string
      - type: string
        pattern: ^<\+input>((\.)((executionInput\(\))|(allowedValues|default|regex)\(.+?\)))*$
        minLength: 1
$schema: http://json-schema.org/draft-07/schema#
properties:
  description:
    desc: This is the description for S3UrlStoreConfig
