title: TerragruntConfigFilesWrapper
type: object
required:
- store
properties:
  moduleSource:
    $ref: module-source.yaml
  store:
    $ref: store-config-wrapper.yaml
  description:
    desc: This is the description for TerragruntConfigFilesWrapper
$schema: http://json-schema.org/draft-07/schema#
