title: TerragruntModuleConfig
type: object
required:
- path
- terragruntRunType
properties:
  path:
    type: string
  terragruntRunType:
    type: string
    enum:
    - RunAll
    - RunModule
  description:
    desc: This is the description for TerragruntModuleConfig
$schema: http://json-schema.org/draft-07/schema#
