title: TerragruntBackendConfig
type: object
properties:
  type:
    type: string
  description:
    desc: This is the description for TerragruntBackendConfig
$schema: http://json-schema.org/draft-07/schema#
allOf:
- if:
    properties:
      type:
        const: Inline
  then:
    properties:
      spec:
        $ref: inline-terragrunt-backend-config-spec.yaml
- if:
    properties:
      type:
        const: Remote
  then:
    properties:
      spec:
        $ref: remote-terragrunt-backend-config-spec.yaml
