title: FlagConfigurationStepInfo
allOf:
- $ref: ../../common/step-spec-type.yaml
- type: object
  required:
  - environment
  - feature
  - instructions
  properties:
    environment:
      type: string
    feature:
      type: string
    instructions:
      oneOf:
      - type: array
        items:
          $ref: patch-instruction.yaml
      - type: string
        pattern: ^<\+input>((\.)((executionInput\(\))|(allowedValues|default|regex)\(.+?\)))*$
        minLength: 1
$schema: http://json-schema.org/draft-07/schema#
type: object
required:
- environment
- feature
- instructions
properties:
  environment:
    type: string
  feature:
    type: string
  instructions:
    oneOf:
    - type: array
      items:
        $ref: patch-instruction.yaml
    - type: string
      pattern: ^<\+input>((\.)((executionInput\(\))|(allowedValues|default|regex)\(.+?\)))*$
      minLength: 1
  description:
    desc: This is the description for FlagConfigurationStepInfo
