title: AmazonS3ArtifactConfig
allOf:
- $ref: artifact-config.yaml
- type: object
  required:
  - bucketName
  - connectorRef
  properties:
    bucketName:
      type: string
      minLength: 1
    connectorRef:
      type: string
    filePath:
      type: string
    filePathRegex:
      type: string
    region:
      type: string
- oneOf:
  - required:
    - filePath
  - required:
    - filePathRegex
$schema: http://json-schema.org/draft-07/schema#
properties:
  description:
    desc: This is the description for AmazonS3ArtifactConfig
