title: AzureArtifactsConfig
allOf:
- $ref: artifact-config.yaml
- type: object
  required:
  - connectorRef
  - feed
  - package
  - packageType
  - scope
  properties:
    connectorRef:
      type: string
      minLength: 1
    feed:
      type: string
      minLength: 1
    package:
      type: string
      minLength: 1
    packageType:
      type: string
      enum:
      - maven
      - nuget
      - upack
    project:
      type: string
    scope:
      type: string
      enum:
      - project
      - org
    version:
      type: string
    versionRegex:
      type: string
- oneOf:
  - required:
    - versionRegex
  - required:
    - version
$schema: http://json-schema.org/draft-07/schema#
properties:
  description:
    desc: This is the description for AzureArtifactsConfig
