title: ConfigFileAttributeStepParameters
type: object
properties:
  store:
    $ref: store-config-wrapper-parameters.yaml
  description:
    desc: This is the description for ConfigFileAttributeStepParameters
$schema: http://json-schema.org/draft-07/schema#
