title: ConfigFileAttributes
type: object
required:
- store
properties:
  configFileAttributeStepParameters:
    $ref: config-file-attribute-step-parameters.yaml
  store:
    $ref: ../../steps/cd/store-config-wrapper.yaml
  description:
    desc: This is the description for ConfigFileAttributes
$schema: http://json-schema.org/draft-07/schema#
