title: ConfigFileOverrideSetWrapper
type: object
properties:
  overrideSet:
    $ref: config-file-override-sets.yaml
  description:
    desc: This is the description for ConfigFileOverrideSetWrapper
$schema: http://json-schema.org/draft-07/schema#
