title: CustomDeploymentServiceSpec
allOf:
- $ref: service-spec.yaml
- type: object
  required:
  - customDeploymentRef
  properties:
    customDeploymentRef:
      minLength: 1
      $ref: step-template-ref.yaml
$schema: http://json-schema.org/draft-07/schema#
properties:
  description:
    desc: This is the description for CustomDeploymentServiceSpec
