title: CustomDeploymentInstanceAttributes
type: object
required:
- jsonPath
- name
properties:
  description:
    type: string
    desc: This is the description for CustomDeploymentInstanceAttributes
  jsonPath:
    type: string
    minLength: 1
  name:
    type: string
    minLength: 1
$schema: http://json-schema.org/draft-07/schema#
