title: CustomDeploymentConfig
type: object
required:
- execution
- infrastructure
properties:
  execution:
    $ref: custom-deployment-execution-config.yaml
  infrastructure:
    $ref: custom-deployment-infra-config.yaml
  metadata:
    type: string
  description:
    desc: This is the description for CustomDeploymentConfig
$schema: http://json-schema.org/draft-07/schema#
