title: CustomDeploymentInfraConfig
type: object
required:
- fetchInstancesScript
- instanceAttributes
- instancesListPath
properties:
  fetchInstancesScript:
    minLength: 1
    $ref: custom-deployment-fetch-instances-script-config.yaml
  instanceAttributes:
    type: array
    items:
      $ref: custom-deployment-instance-attributes.yaml
    minLength: 1
  instancesListPath:
    type: string
    minLength: 1
  variables:
    type: array
    items:
      oneOf:
      - $ref: custom-deployment-connector-ng-variable.yaml
      - $ref: custom-deployment-number-ng-variable.yaml
      - $ref: custom-deployment-secret-ng-variable.yaml
      - $ref: custom-deployment-string-ng-variable.yaml
  description:
    desc: This is the description for CustomDeploymentInfraConfig
$schema: http://json-schema.org/draft-07/schema#
