title: DeploymentMetaData
type: object
discriminator: deploymentType
$schema: http://json-schema.org/draft-07/schema#
properties:
  description:
    desc: This is the description for DeploymentMetaData
