$schema: http://json-schema.org/draft-07/schema#
title: DeploymentStageNode
type: object
required:
- failure
- type
properties:
  desc:
    type: string
    description: The stage description.
  id:
    type: string
    description: The unique stage identifier.
    pattern: ^[a-zA-Z_][0-9a-zA-Z_]{0,127}$
  name:
    type: string
    description: The stage name.
    pattern: ^[a-zA-Z_0-9-.][-0-9a-zA-Z_\s.]{0,127}$
  strategy:
    $ref: ../../common/strategy.yaml
    description: The stage execution strategy.
  delegates:
    $ref: ../../common/delegate.yaml
    description: Configures the delegate matching logic.
  type:
    type: string
    description: The stage type.
    enum:
      - deployment
  when:
    description: The stage conditional logic.
    type: string
  failure:
    $ref: ../../common/failure_list.yaml
  variables:
    type: object
    description: Variables defines the pipeline variable parameters.
    additionalProperties:
      oneOf:
        - "$ref": ../../common/string-variable.yaml
        - "$ref": ../../common/number-variable.yaml
        - "$ref": ../../common/array-variable.yaml
        - "$ref": ../../common/boolean-variable.yaml
        - "$ref": ../../common/object-variable.yaml
        - "$ref": ../../common/secret-variable.yaml
  timeout:
    type: string
    pattern: ^(([1-9])+\d+[s])|(((([1-9])+\d*[mhwd])+([\s]?\d+[smhwd])*)|(.*<\+.*>(?!.*\.executionInput\(\)).*)|(^$))$
  labels:
    type: object
    additionalProperties:
      type: string
  skip_instances:
    oneOf:
      - type: boolean
      - type: string
  spec:
    $ref: ./deployment-stage-config.yaml
allOf:
- if:
    properties:
      type:
        const: deployment
  then:
    properties:
      spec:
        $ref: ./deployment-stage-config.yaml
