$schema: http://json-schema.org/draft-07/schema#
title: DeploymentStageConfig
type: object
required:
- steps
properties:
  deployment_template:
    $ref: step-template-ref.yaml
  steps:
    type: array
    items:
      configRef: ./deployment-stage-spec-element-wrapper-config.yaml/steps
    maxItems: 256
    minItems: 1
  rollback_steps:
    type: array
    items:
      configRef: ./deployment-stage-spec-element-wrapper-config.yaml/steps
    maxItems: 256
    minItems: 1
  environmentGroup:
    $ref: environment-group-yaml.yaml
  environments:
    $ref: environments-yaml.yaml
  gitops_enabled:
    type: boolean
  services:
    $ref: services-yaml.yaml
  desc:
    type: string
    description: This is the description for DeploymentStageConfig
allOf:
- oneOf:
  - required:
    - service
  - required:
    - services
- oneOf:
  - required:
    - environment
  - required:
    - environmentGroup
  - required:
    - environments
