title: EnvironmentGroupMetadata
type: object
properties:
  parallel:
    oneOf:
      - type: boolean
      - type: string
        pattern: (<\+.+>.*|^$)
  description:
    desc: This is the description for EnvironmentGroupMetadata
$schema: http://json-schema.org/draft-07/schema#
