title: SimplifiedEnvironmentYaml
type: object
properties:
  deploy-to-all:
    oneOf:
    - type: boolean
    - type: string
      pattern: ^<\+input>((\.)((executionInput\(\))|(allowedValues|default|regex)\(.+?\)))*$
      minLength: 1
  inputs:
    oneOf:
    - $ref: ../../common/json-node.yaml
    - type: string
      pattern: (^<\+input>((\.)((executionInput\(\))|(allowedValues|default|regex)\(.+?\)))*$|^$)
  ref:
    type: string
    pattern: ^(?=\s*\S).*$
  use-from-stage:
    $ref: environment-infra-use-from-stage.yaml
  filters:
    oneOf:
    - type: array
      items:
        $ref: env-infra-filter-yaml.yaml
    - type: string
      pattern: ^<\+input>((\.)((executionInput\(\))|(allowedValues|default|regex)\(.+?\)))*$
      minLength: 1
  git-ops-clusters:
    oneOf:
    - type: array
      items:
        $ref: cluster-yaml.yaml
    - type: string
      pattern: ^<\+input>((\.)((executionInput\(\))|(allowedValues|default|regex)\(.+?\)))*$
      minLength: 1
  infra-defs:
    oneOf:
    - type: array
      items:
        $ref: infra-structure-definition-yaml.yaml
    - type: string
      pattern: (^<\+input>((\.)((executionInput\(\))|(allowedValues|default|regex)\(.+?\)))*$|^$)
  provisioner:
    $ref: execution-element-config.yaml
  service-override-inputs:
    oneOf:
    - $ref: ../../common/json-node.yaml
    - type: string
      pattern: (^<\+input>((\.)((executionInput\(\))|(allowedValues|default|regex)\(.+?\)))*$|^$)
  services-overrides:
    type: array
    items:
      $ref: service-override-inputs-yaml.yaml
  desc:
    description: This is the description for SimplifiedEnvironmentYaml
$schema: http://json-schema.org/draft-07/schema#
