title: EnvironmentYaml
type: object
required:
  - ref
  - infra
properties:
  ref:
    type: string
  inputs:
    $ref: ../../common/inputs.yaml
  infra:
    oneOf:
      - type: array
        items:
          $ref: infra-structure-definition-yaml.yaml
      - type: string
        pattern: ^<\+inputs\..*>$
$schema: http://json-schema.org/draft-07/schema#
