title: EnvironmentYaml
type: object
required:
- identifier
- name
- type
properties:
  description:
    type: string
    desc: This is the description for EnvironmentYaml
  identifier:
    type: string
  name:
    type: string
  tags:
    type: object
    additionalProperties:
      type: string
  type:
    type: string
    enum:
    - PreProduction
    - Production
$schema: http://json-schema.org/draft-07/schema#
