title: EnvironmentsYaml
type: object
properties:
  values:
    oneOf:
      - type: array
        items:
          $ref: environment-yaml.yaml
      - type: string
        pattern: ^<\+inputs\..*>$
  inherit:
    $ref: inherit-environment.yaml
  filters:
    type: array
    items:
      $ref: env-infra-filter-yaml.yaml
  sequential:
    oneOf:
      - type: boolean
      - type: string
  desc:
    description: This is the description for EnvironmentsYaml
anyOf:
  - values
  - inherit
  - filters
$schema: http://json-schema.org/draft-07/schema#