title: EnvironmentsMetadata
type: object
properties:
  parallel:
    oneOf:
    - type: boolean
    - type: string
      pattern: (^<\+input>((\.)((executionInput\(\))|(allowedValues|default|regex)\(.+?\)))*$|^$)    
  description:
    desc: This is the description for EnvironmentsMetadata
$schema: http://json-schema.org/draft-07/schema#
