title: EnvironmentInfraUseFromStage
type: object
required:
- stage
properties:
  metadata:
    type: string
  stage:
    type: string
    pattern: ^[a-zA-Z_][0-9a-zA-Z_]{0,127}$
  description:
    desc: This is used when you want to propagate environment from one of the previous stages.
$schema: http://json-schema.org/draft-07/schema#
