title: ExecutionElementConfig
type: object
required:
- steps
properties:
  rollbackSteps:
    type: array
    items:
      $ref: execution-wrapper-config.yaml
  steps:
    type: array
    items:
      $ref: execution-wrapper-config.yaml
    maxItems: 2147483647
    minItems: 1
  description:
    desc: This is the description for ExecutionElementConfig
$schema: http://json-schema.org/draft-07/schema#
