title: GoogleCloudStorageArtifactConfig
allOf:
- $ref: artifact-config.yaml
- type: object
  required:
  - artifactPath
  - bucket
  - connectorRef
  - project
  properties:
    artifactPath:
      type: string
    bucket:
      type: string
    connectorRef:
      type: string
    project:
      type: string
$schema: http://json-schema.org/draft-07/schema#
properties:
  description:
    desc: This is the description for GoogleCloudStorageArtifactConfig
