title: InheritEnvironment
type: object
required:
  - stage
properties:
  stage:
    type: string
  with:
    type: array
    items:
      $ref: inherit-env-with-config.yaml
  desc:
    description: This is the description for InheritEnvironment
$schema: http://json-schema.org/draft-07/schema#
