title: InheritEnvironmentWithConfig
type: object
required:
  - env
  - infra
properties:
  env:
    type: string
  infra:
    type: string
  inputs:
    $ref: ../../common/inputs.yaml
$schema: http://json-schema.org/draft-07/schema#