title: InheritEnvironment
type: object
required:
  - stage
properties:
  stage:
    type: string
    pattern: ^[a-zA-Z_][0-9a-zA-Z_]{0,127}$
  with:
    type: array
    items:
      $ref: inherit-env-with-config.yaml
  desc:
    description: This is the description for InheritEnvironment
$schema: http://json-schema.org/draft-07/schema#
