title: ManifestConfigurations
type: object
properties:
  primaryManifestRef:
    type: string
  description:
    desc: This is the description for ManifestConfigurations
$schema: http://json-schema.org/draft-07/schema#
