title: NexusRegistryNpmConfig
allOf:
- $ref: nexus-registry-config-spec.yaml
- type: object
  required:
  - packageName
  properties:
    packageName:
      type: string
$schema: http://json-schema.org/draft-07/schema#
properties:
  description:
    desc: This is the description for NexusRegistryNpmConfig
