title: NexusRegistryMavenConfig
allOf:
- $ref: nexus-registry-config-spec.yaml
- type: object
  required:
  - artifactId
  - groupId
  properties:
    artifactId:
      type: string
    classifier:
      type: string
    extension:
      type: string
    groupId:
      type: string
$schema: http://json-schema.org/draft-07/schema#
properties:
  description:
    desc: This is the description for NexusRegistryMavenConfig
