title: ParallelStepElementConfig
type: array
items:
  configRef: ./deployment-stage-spec-element-wrapper-config.yaml/steps
$schema: http://json-schema.org/draft-07/schema#
properties:
  description:
    desc: This is the description for ParallelStepElementConfig
