title: ServiceConfig
type: object
properties:
  service:
    $ref: service-yaml.yaml
  defination:
    $ref: service-definition.yaml
  name:
    type: string
  stage-overrides:
    $ref: stage-overrides-config.yaml
  use-from-stage:
    $ref: service-use-from-stage.yaml
  description:
    desc: This is the description for ServiceConfig
$schema: http://json-schema.org/draft-07/schema#
allOf:
- oneOf:
  - required:
    - use-from-stage
  - required:
    - service
  - required:
    - name
- oneOf:
  - required:
    - use-from-stage
  - required:
    - defination
