title: StepGroupElementConfig
type: object
required:
- identifier
- name
properties:
  delegateSelectors:
    oneOf:
    - type: array
      items:
        type: string
    - type: string
      pattern: (<\+.+>.*)
      minLength: 1
  failureStrategies:
    oneOf:
    - type: array
      items:
        $ref: ../../common/failure-strategy-config.yaml
    - type: string
      pattern: ^<\+input>$
      minLength: 1
  identifier:
    type: string
    pattern: ^[a-zA-Z_][0-9a-zA-Z_]{0,127}$
  name:
    type: string
    pattern: ^[a-zA-Z_0-9-.][-0-9a-zA-Z_\s.]{0,127}$
  sharedPaths:
    oneOf:
    - type: array
      items:
        type: string
    - type: string
      pattern: ^<\+input>((\.)((executionInput\(\))|(allowedValues|default|regex)\(.+?\)))*$
      minLength: 1
  stepGroupInfra:
    oneOf:
    - $ref: ../../common/k8s-direct-infra.yaml
  steps:
    type: array
    items:
      configRef: ./deployment-stage-spec-element-wrapper-config.yaml/steps
    maxItems: 256
    minItems: 1
  strategy:
    oneOf:
    - $ref: ../../common/strategy-config.yaml
    - type: string
      pattern: ^<\+input>$
      minLength: 1
  template:
    $ref: ../../steps/custom/template-link-config.yaml
  when:
    oneOf:
    - $ref: ../../common/step-when-condition.yaml
    - type: string
      pattern: ^<\+input>$
      minLength: 1
  description:
    desc: This is the description for StepGroupElementConfig
  variables:
    type: array
    items:
      oneOf:
      - $ref: ../../common/number-ng-variable.yaml
      - $ref: ../../common/secret-ng-variable.yaml
      - $ref: ../../common/string-ng-variable.yaml
$schema: http://json-schema.org/draft-07/schema#
allOf:
- oneOf:
  - required:
    - template
  - required:
    - steps
