# Pipeline with advanced container configuration
pipeline:
  stages:
  - steps:
    - run:
        script: |
          npm install
          npm test
        container:
          image: node:18
          pull: if-not-exists
          memory: 2gb
          cpu: 2
          env:
            NODE_ENV: test
