title: ExecutionWrapperConfig
type: object
properties:
  parallel:
    $ref: parallel-step-element-config.yaml
  step:
    oneOf:
    - $ref: ../../common/step-element-config.yaml
    - $ref: ../../steps/common/run-step-node.yaml
    - $ref: ../../steps/common/plugin-step-node.yaml # if the manager receives this as iacm plugin step then all good, if not we will need to use the iacm plugin step
    - $ref: ../../steps/common/action-step-node.yaml
    - $ref: ../../steps/iacm/iacmterraform-plugin-step-node.yaml
    - $ref: ../../steps/iacm/iacmapproval-step-node.yaml
    - $ref: ../../steps/common/template-step-node.yaml
    - $ref: ../../steps/ci/git-clone-step-node.yaml
    - $ref: ../../steps/iacm/iacmopentofu-plugin-step-node.yaml
    - $ref: ../../steps/iacm/iacmtfsec-plugin-step-node.yaml
    - $ref: ../../steps/iacm/iacmtflint-plugin-step-node.yaml
    - $ref: ../../steps/iacm/iacmtfcompliance-plugin-step-node.yaml
    - $ref: ../../steps/iacm/iacmcheckov-plugin-step-node.yaml
    - $ref: ../../steps/common/wiz-scan-node.yaml
    - $ref: ../../steps/common/custom-ingest-scan-node.yaml
    - $ref: ../../steps/common/security-node.yaml
    - $ref: ../../steps/common/checkov-scan-node.yaml
    - $ref: ../../steps/common/snyk-scan-node.yaml

  description:
    desc: This is the description for ExecutionWrapperConfig
$schema: http://json-schema.org/draft-07/schema#
