title: ExecutionWrapperConfig
type: object
properties:
  parallel:
    $ref: parallel-step-element-config.yaml
  step:
    oneOf:
    - $ref: ../../common/step-element-config.yaml
    - $ref: ../../steps/common/run-step-node.yaml
    - $ref: ../../steps/common/plugin-step-node.yaml # if the manager receives this as iacm plugin step then all good, if not we will need to use the iacm plugin step
    - $ref: ../../steps/common/action-step-node.yaml
    - $ref: ../../steps/iacm/iacmterraform-plugin-step-node.yaml
    - $ref: ../../steps/iacm/iacmapproval-step-node.yaml
    - $ref: ../../steps/common/template-step-node.yaml
    - $ref: ../../steps/ci/git-clone-step-node.yaml
    - $ref: ../../steps/iacm/iacmopentofu-plugin-step-node.yaml
    - $ref: ../../steps/iacm/iacmtfsec-plugin-step-node.yaml
    - $ref: ../../steps/iacm/iacmtflint-plugin-step-node.yaml
    - $ref: ../../steps/iacm/iacmtfcompliance-plugin-step-node.yaml
    - $ref: ../../steps/iacm/iacmcheckov-plugin-step-node.yaml
    - $ref: ../../steps/common/wiz-scan-node.yaml
    - $ref: ../../steps/common/custom-ingest-scan-node.yaml
    - $ref: ../../steps/common/security-node.yaml
    - $ref: ../../steps/common/checkov-scan-node.yaml
    - $ref: ../../steps/common/snyk-scan-node.yaml
    - $ref: ../../steps/iacm/iacmmoduletest-plugin-step-node.yaml
    - $ref: ../../steps/common/checkmarx-one-scan-node.yaml
    - $ref: ../../steps/iacm/iacmterragrunt-plugin-step-node.yaml
    - $ref: ../../steps/iacm/iacmansible-plugin-step-node.yaml
    - $ref: ../../steps/custom/queue-step-node.yaml
    - $ref: ../../steps/custom/shell-script-step-node.yaml
    - $ref: ../../steps/custom/container-step-node.yaml
    - $ref: ../../steps/custom/http-step-node.yaml
    - $ref: ../../steps/custom/email-step-node.yaml
    - $ref: ../../steps/custom/wait-step-node.yaml
    - $ref: ../../steps/custom/harness-approval-step-node.yaml
    - $ref: ../../steps/custom/custom-approval-step-node.yaml
    - $ref: ../../steps/custom/jira-approval-step-node.yaml
    - $ref: ../../steps/custom/service-now-approval-step-node.yaml
    - $ref: ../../steps/custom/jira-create-step-node.yaml
    - $ref: ../../steps/custom/jira-update-step-node.yaml
    - $ref: ../../steps/custom/barrier-step-node.yaml
    - $ref: ../../steps/custom/policy-step-node.yaml
    - $ref: ../../steps/custom/service-now-create-step-node.yaml
    - $ref: ../../steps/custom/service-now-update-step-node.yaml
    - $ref: ../../steps/custom/service-now-import-set-step-node.yaml

  description:
    desc: This is the description for ExecutionWrapperConfig
$schema: http://json-schema.org/draft-07/schema#
