title: PipelineStageConfig
type: object
required:
- org
- pipeline
- project
properties:
  inputSetReferences:
    type: array
    items:
      type: string
  inputs:
    oneOf:
    - $ref: ../../common/json-node.yaml
    - type: string
      pattern: ^<\+input>((\.)((executionInput\(\))|(allowedValues|default|regex)\(.+?\)))*$
      minLength: 1
  org:
    type: string
  outputs:
    type: array
    items:
      $ref: pipeline-stage-outputs.yaml
  pipeline:
    type: string
  pipelineInputs:
    oneOf:
    - $ref: ../../common/json-node.yaml
    - type: string
      pattern: ^<\+input>((\.)((executionInput\(\))|(allowedValues|default|regex)\(.+?\)))*$
      minLength: 1
  project:
    type: string
  description:
    desc: This is the description for PipelineStageConfig
$schema: http://json-schema.org/draft-07/schema#
