version: 1
kind: template
spec:
  type: pipeline
  spec:
    stages:
      - name: custom
        type: custom
        spec:
          steps:
            - name: http
              type: http
              spec:
                url: https://www.google.com
                method: GET
                input_vars: [ ]
                headers: [ ]
                output_vars: [ ]
                body: null
              timeout: 10s
