version: 1
kind: template
spec:
  type: pipeline
  spec:
    stages:
      - name: custom
        type: custom
        spec:
          steps:
            - name: http
              type: http
              spec:
                url: https://www.google.com
                method: GET
                inputVariables: [ ]
                headers: [ ]
                outputVariables: [ ]
                requestBody: null
              timeout: 10s
