title: CustomStageSpecElementConfig
type: object
required:
- steps
properties:
  rollbackSteps:
    type: array
    items:
      $ref: custom-stage-spec-element-wrapper-config.yaml
  steps:
    type: array
    items:
      $ref: custom-stage-spec-element-wrapper-config.yaml
    maxItems: 256
    minItems: 1
$schema: http://json-schema.org/draft-07/schema#
