title: CustomStageSpecElementConfig
type: object
required:
  - steps
properties:
  rollback_steps:
    type: array
    items:
      configRef: ./custom-stage-spec-element-wrapper-config.yaml/steps
  steps:
    type: array
    items:
      configRef: ./custom-stage-spec-element-wrapper-config.yaml/steps
    maxItems: 256
    minItems: 1
$schema: http://json-schema.org/draft-07/schema#
