title: FailureStrategyActionConfigV1
description: Action configuration for failure strategy. Can be a string shorthand or a detailed object.
oneOf:
  - type: string
    enum:
      - abort
      - ignore
      - success
      - stage-rollback
      - pipeline-rollback
      - fail
  - type: object
    properties:
      retry:
        $ref: ./retry-failure-spec-config.yaml
      manual-intervention:
        $ref: ./manual-failure-spec-config.yaml
      abort:
        description: Abort the execution.
        type: object
      ignore:
        description: Ignore the failure and continue.
        type: object
      success:
        description: Mark the execution as success.
        type: object
      stage-rollback:
        description: Rollback the stage.
        type: object
      pipeline-rollback:
        description: Rollback the pipeline.
        type: object
      fail:
        description: Mark the execution as failed.
        type: object
      retry-step-group:
        $ref: ./retry-step-group-failure-spec-config.yaml
$schema: http://json-schema.org/draft-07/schema#
