title: PolicyConfig
type: object
required:
- policy_sets
properties:
  policy_sets:
    oneOf:
    - type: array
      items:
        type: string
    - type: string
      pattern: (<\+inputs\..+>.*)
      minLength: 1
  description:
    desc: This is the description for PolicyConfig
metadata:
  inputProperties:
    type: object
    internalType: policy_config
$schema: http://json-schema.org/draft-07/schema#
