title: PolicyConfig
type: object
required:
  - policy_sets
properties:
  policy_sets:
    oneOf:
    - type: array
      items:
        type: string
    - type: string
      minLength: 1
$schema: http://json-schema.org/draft-07/schema#
