title: ParallelStepElementConfig
type: array
items:
  $ref: execution-wrapper-config.yaml
$schema: http://json-schema.org/draft-07/schema#
properties:
  description:
    desc: This is the description for ParallelStepElementConfig
