title: ExecutionWrapperConfig
type: object
properties:
  parallel:
    $ref: parallel-step-element-config.yaml
  step:
    oneOf:
    - $ref: ../../common/step-element-config.yaml
    - $ref: ../../steps/ci/save-cache-s3-node.yaml
    - $ref: ../../steps/ci/build-and-push-docker-node.yaml
    - $ref: ../../steps/ci/brakeman-scan-node.yaml
    - $ref: ../../steps/ci/mend-scan-node.yaml
    - $ref: ../../steps/ci/fortify-on-demand-scan-node.yaml
    - $ref: ../../steps/ci/jfrog-xray-scan-node.yaml
    - $ref: ../../steps/ci/grype-scan-node.yaml
    - $ref: ../../steps/ci/black-duck-scan-node.yaml
    - $ref: ../../steps/ci/run-test-step-node.yaml
    - $ref: ../../steps/ci/openvas-scan-node.yaml
    - $ref: ../../steps/ci/owasp-scan-node.yaml
    - $ref: ../../steps/ci/aqua-trivy-scan-node.yaml
    - $ref: ../../steps/common/codeql-scan-node.yaml
    - $ref: ../../steps/common/aws-security-hub-scan-node.yaml
    - $ref: ../../steps/common/fossa-scan-node.yaml
    - $ref: ../../steps/ci/nmap-scan-node.yaml
    - $ref: ../../steps/ci/restore-cache-gcsnode.yaml
    - $ref: ../../steps/ci/nessus-scan-node.yaml
    - $ref: ../../steps/ci/build-and-push-acrnode.yaml
    - $ref: ../../steps/ci/data-theorem-scan-node.yaml
    - $ref: ../../steps/ci/docker-content-trust-scan-node.yaml
    - $ref: ../../steps/ci/security-node.yaml
    - $ref: ../../steps/ci/reapsaw-scan-node.yaml
    - $ref: ../../steps/ci/ssca-orchestration-step-node.yaml
    - $ref: ../../steps/ci/artifactory-upload-node.yaml
    - $ref: ../../steps/ci/sysdig-scan-node.yaml
    - $ref: ../../steps/common/semgrep-scan-node.yaml
    - $ref: ../../steps/ci/sniper-scan-node.yaml
    - $ref: ../../steps/ci/git-clone-step-node.yaml
    - $ref: ../../steps/ci/burp-scan-node.yaml
    - $ref: ../../steps/ci/qualys-scan-node.yaml
    - $ref: ../../steps/ci/sonarqube-scan-node.yaml
    - $ref: ../../steps/ci/gcsupload-node.yaml
    - $ref: ../../steps/ci/s3-upload-node.yaml
    - $ref: ../../steps/ci/zap-scan-node.yaml
    - $ref: ../../steps/ci/aws-ecr-scan-node.yaml
    - $ref: snyk-scan-node.yaml
    - $ref: ../../steps/ci/veracode-scan-node.yaml
    - $ref: ../../steps/ci/tenable-scan-node.yaml
    - $ref: ../../steps/ci/restore-cache-s3-node.yaml
    - $ref: ../../steps/ci/nikto-scan-node.yaml
    - $ref: ../../steps/ci/bandit-scan-node.yaml
    - $ref: ../../steps/common/action-step-node.yaml
    - $ref: ../../steps/common/plugin-step-node.yaml
    - $ref: ../../steps/ci/bitrise-step-node.yaml
    - $ref: ../../steps/ci/build-and-push-ecrnode.yaml
    - $ref: ../../steps/ci/checkmarx-scan-node.yaml
    - $ref: ../../steps/ci/clair-scan-node.yaml
    - $ref: ../../steps/ci/prisma-cloud-scan-node.yaml
    - $ref: ../../steps/ci/save-cache-gcsnode.yaml
    - $ref: ../../steps/ci/build-and-push-gcrnode.yaml
    - $ref: ../../steps/common/custom-ingest-scan-node.yaml
    - $ref: ../../steps/common/gitleaks-scan-node.yaml
    - $ref: ../../steps/ci/ssca-enforcement-step-node.yaml
    - $ref: ../../steps/common/run-step-node.yaml
    - $ref: ../../steps/ci/shift-left-scan-node.yaml
    - $ref: ../../steps/ci/metasploit-scan-node.yaml
    - $ref: ../../steps/common/background-step-node.yaml
    - $ref: ../../steps/ci/prowler-scan-node.yaml
    - $ref: ../../steps/ci/nexus-iqscan-node.yaml
    - $ref: ../../steps/custom/template-step-node.yaml
    - $ref: ../../steps/custom/policy-step-node.yaml
    - $ref: ../../steps/custom/wait-step-node.yaml
  stepGroup:
    $ref: step-group-element-config.yaml
  description:
    desc: This is the description for ExecutionWrapperConfig
$schema: http://json-schema.org/draft-07/schema#
