title: ExecutionWrapperConfig
type: object
properties:
  parallel:
    $ref: parallel-step-element-config.yaml
  step:
    oneOf:
      - $ref: ../../common/step-element-config.yaml
      - $ref: ../../steps/ci/artifactory-upload-node.yaml
      - $ref: ../../steps/ci/bitrise-step-node.yaml
      - $ref: ../../steps/ci/build-and-push-acrnode.yaml
      - $ref: ../../steps/ci/build-and-push-docker-node.yaml
      - $ref: ../../steps/ci/build-and-push-ecrnode.yaml
      - $ref: ../../steps/ci/build-and-push-gcrnode.yaml
      - $ref: ../../steps/ci/build-and-push-garnode.yaml
      - $ref: ../../steps/ci/gcsupload-node.yaml
      - $ref: ../../steps/ci/git-clone-step-node.yaml
      - $ref: ../../steps/ci/restore-cache-gcsnode.yaml
      - $ref: ../../steps/ci/restore-cache-s3-node.yaml
      - $ref: ../../steps/ci/run-test-step-node.yaml
      - $ref: ../../steps/ci/s3-upload-node.yaml
      - $ref: ../../steps/ci/save-cache-gcsnode.yaml
      - $ref: ../../steps/ci/save-cache-s3-node.yaml
      - $ref: ../../steps/ci/ssca-enforcement-step-node.yaml
      - $ref: ../../steps/ci/ssca-orchestration-step-node.yaml
      - $ref: ../../steps/common/action-step-node.yaml
      - $ref: ../../steps/common/aqua-trivy-scan-node.yaml
      - $ref: ../../steps/common/aws-ecr-scan-node.yaml
      - $ref: ../../steps/common/aws-security-hub-scan-node.yaml
      - $ref: ../../steps/common/background-step-node.yaml
      - $ref: ../../steps/common/bandit-scan-node.yaml
      - $ref: ../../steps/common/black-duck-scan-node.yaml
      - $ref: ../../steps/common/brakeman-scan-node.yaml
      - $ref: ../../steps/common/burp-scan-node.yaml
      - $ref: ../../steps/common/checkmarx-scan-node.yaml
      - $ref: ../../steps/common/clair-scan-node.yaml
      - $ref: ../../steps/common/codeql-scan-node.yaml
      - $ref: ../../steps/common/coverity-scan-node.yaml
      - $ref: ../../steps/common/custom-ingest-scan-node.yaml
      - $ref: ../../steps/common/data-theorem-scan-node.yaml
      - $ref: ../../steps/common/docker-content-trust-scan-node.yaml
      - $ref: ../../steps/common/fortify-on-demand-scan-node.yaml
      - $ref: ../../steps/common/fossa-scan-node.yaml
      - $ref: ../../steps/common/gitleaks-scan-node.yaml
      - $ref: ../../steps/common/grype-scan-node.yaml
      - $ref: ../../steps/common/jfrog-xray-scan-node.yaml
      - $ref: ../../steps/common/mend-scan-node.yaml
      - $ref: ../../steps/common/metasploit-scan-node.yaml
      - $ref: ../../steps/common/nessus-scan-node.yaml
      - $ref: ../../steps/common/nexus-iqscan-node.yaml
      - $ref: ../../steps/common/nikto-scan-node.yaml
      - $ref: ../../steps/common/nmap-scan-node.yaml
      - $ref: ../../steps/common/openvas-scan-node.yaml
      - $ref: ../../steps/common/owasp-scan-node.yaml
      - $ref: ../../steps/common/plugin-step-node.yaml
      - $ref: ../../steps/common/prisma-cloud-scan-node.yaml
      - $ref: ../../steps/common/prowler-scan-node.yaml
      - $ref: ../../steps/common/qualys-scan-node.yaml
      - $ref: ../../steps/common/reapsaw-scan-node.yaml
      - $ref: ../../steps/common/run-step-node.yaml
      - $ref: ../../steps/common/security-node.yaml
      - $ref: ../../steps/common/semgrep-scan-node.yaml
      - $ref: ../../steps/common/shift-left-scan-node.yaml
      - $ref: ../../steps/common/sniper-scan-node.yaml
      - $ref: ../../steps/common/snyk-scan-node.yaml
      - $ref: ../../steps/common/sonarqube-scan-node.yaml
      - $ref: ../../steps/common/sysdig-scan-node.yaml
      - $ref: ../../steps/common/tenable-scan-node.yaml
      - $ref: ../../steps/common/veracode-scan-node.yaml
      - $ref: ../../steps/common/zap-scan-node.yaml
      - $ref: ../../steps/custom/policy-step-node.yaml
      - $ref: ../../steps/custom/template-step-node.yaml
      - $ref: ../../steps/custom/wait-step-node.yaml
      - $ref: ../../steps/common/slsa-verification-step-node.yaml
  stepGroup:
    $ref: step-group-element-config.yaml
  description:
    desc: This is the description for ExecutionWrapperConfig
$schema: http://json-schema.org/draft-07/schema#
