title: ExecutionWrapperConfig
type: object
properties:
  parallel:
    $ref: parallel-step-element-config.yaml
  step:
    oneOf:
    - $ref: ../../common/step-element-config.yaml
    - $ref: nessus-scan-node.yaml
    - $ref: prisma-cloud-scan-node.yaml
    - $ref: save-cache-s3-node.yaml
    - $ref: grype-scan-node.yaml
    - $ref: fortify-on-demand-scan-node.yaml
    - $ref: ../../steps/ci/action-step-node.yaml
    - $ref: nmap-scan-node.yaml
    - $ref: bandit-scan-node.yaml
    - $ref: qualys-scan-node.yaml
    - $ref: aws-ecr-scan-node.yaml
    - $ref: burp-scan-node.yaml
    - $ref: s3-upload-node.yaml
    - $ref: ../../steps/ci/bitrise-step-node.yaml
    - $ref: save-cache-gcsnode.yaml
    - $ref: metasploit-scan-node.yaml
    - $ref: mend-scan-node.yaml
    - $ref: nexus-iqscan-node.yaml
    - $ref: owasp-scan-node.yaml
    - $ref: build-and-push-acrnode.yaml
    - $ref: sysdig-scan-node.yaml
    - $ref: restore-cache-s3-node.yaml
    - $ref: zap-scan-node.yaml
    - $ref: sniper-scan-node.yaml
    - $ref: prowler-scan-node.yaml
    - $ref: sonarqube-scan-node.yaml
    - $ref: artifactory-upload-node.yaml
    - $ref: security-node.yaml
    - $ref: checkmarx-scan-node.yaml
    - $ref: ../../steps/ci/run-test-step-node.yaml
    - $ref: clair-scan-node.yaml
    - $ref: data-theorem-scan-node.yaml
    - $ref: openvas-scan-node.yaml
    - $ref: jfrog-xray-scan-node.yaml
    - $ref: ../../steps/ci/git-clone-step-node.yaml
    - $ref: build-and-push-gcrnode.yaml
    - $ref: gcsupload-node.yaml
    - $ref: veracode-scan-node.yaml
    - $ref: ../../steps/common/run-step-node.yaml
    - $ref: ../../steps/common/background-step-node.yaml
    - $ref: build-and-push-ecrnode.yaml
    - $ref: brakeman-scan-node.yaml
    - $ref: aqua-trivy-scan-node.yaml
    - $ref: black-duck-scan-node.yaml
    - $ref: external-scan-node.yaml
    - $ref: snyk-scan-node.yaml
    - $ref: nikto-scan-node.yaml
    - $ref: build-and-push-docker-node.yaml
    - $ref: tenable-scan-node.yaml
    - $ref: restore-cache-gcsnode.yaml
    - $ref: docker-content-trust-scan-node.yaml
    - $ref: ../../steps/ci/plugin-step-node.yaml
    - $ref: reapsaw-scan-node.yaml
    - $ref: shift-left-scan-node.yaml
    - $ref: ../../steps/pie/template-step-node.yaml
    - $ref: ../../steps/pie/policy-step-node.yaml
    - $ref: ../../steps/pie/wait-step-node.yaml
  stepGroup:
    $ref: step-group-element-config.yaml
  description:
    desc: This is the description for ExecutionWrapperConfig
$schema: http://json-schema.org/draft-07/schema#
