title: SlsaConfig
type: object
properties:
  enabled:
    oneOf:
      - type: boolean
      - type: string
        pattern: ^<\+input>((\.)((executionInput\(\))|(allowedValues|default|regex)\(.+?\)))*$
        minLength: 1
  attestation:
    $ref: ../../steps/custom/attestation.yaml
  description:
    desc: This is config to enable SLSA.
$schema: http://json-schema.org/draft-07/schema#