title: SlsaConfig
type: object
properties:
  attestation:
    $ref: attestation-v1.yaml
  enabled:
    oneOf:
    - type: boolean
    - type: string
      pattern: ^<\+input>((\.)((executionInput\(\))|(allowedValues|selectOneFrom|default|regex)\(.+?\)))*$
      minLength: 1
  description:
    desc: This is the description for SlsaConfig
$schema: http://json-schema.org/draft-07/schema#
