title: STOYamlAdvancedSettings
type: object
properties:
  args:
    oneOf:
    - $ref: stoyaml-args.yaml
    - type: string
      pattern: ^<\+input>((\.)((executionInput\(\))|(allowedValues|default|regex)\(.+?\)))*$
      minLength: 1
  fail_on_severity:
    oneOf:
    - type: string
      enum:
      - critical
      - high
      - medium
      - low
      - none
    - type: string
      pattern: ^<\+input>((\.)((executionInput\(\))|(allowedValues|default|regex)\(.+?\)))*$
      minLength: 1
  include_raw:
    oneOf:
    - type: boolean
    - type: string
      pattern: ^<\+input>((\.)((executionInput\(\))|(allowedValues|default|regex)\(.+?\)))*$
      minLength: 1
  log:
    oneOf:
    - $ref: stoyaml-log.yaml
    - type: string
      pattern: ^<\+input>((\.)((executionInput\(\))|(allowedValues|default|regex)\(.+?\)))*$
      minLength: 1
  description:
    desc: This is the description for STOYamlAdvancedSettings
$schema: http://json-schema.org/draft-07/schema#
