title: ExecutionWrapperConfig
type: object
properties:
  parallel:
    $ref: parallel-step-element-config.yaml
  step:
    oneOf:
      - $ref: ../../common/step-element-config.yaml
      - $ref: ../../steps/common/run-step-node.yaml
      - $ref: ../../steps/ci/git-clone-step-node.yaml
      - $ref: ../../steps/common/plugin-step-node.yaml
      - $ref: ../../steps/idp/idpcookiecutter-node.yaml
      - $ref: ../../steps/idp/idpcreaterepo-node.yaml
  description:
    desc: This is the description for ExecutionWrapperConfig
$schema: http://json-schema.org/draft-07/schema#