title: AgentApplicationTargets
type: object
properties:
  agentId:
    oneOf:
    - type: string
    - type: string
      pattern: ^<\+input>((\.)((executionInput\(\))|(allowedValues|default|regex)\(.+?\)))*$
      minLength: 1
  applicationName:
    oneOf:
    - type: array
      items:
        type: string
    - type: string
      pattern: ^<\+input>((\.)((executionInput\(\))|(allowedValues|default|regex)\(.+?\)))*$
      minLength: 1
  description:
    desc: This is the description for AgentApplicationTargets
$schema: http://json-schema.org/draft-07/schema#
