title: AgentApplicationRollbackTargets
type: object
required:
- agentId
- applicationName
properties:
  agentId:
    type: string
  applicationName:
    type: string
  historyId:
    oneOf:
      - type: integer
      - type: string
        pattern: (<\+.+>.*)
        minLength: 1
  rollBackSteps:
    oneOf:
      - type: integer
        minimum: 1
      - type: string
        pattern: (<\+.+>.*)
        minLength: 1
$schema: http://json-schema.org/draft-07/schema#
