title: ArtifactoryStoreConfig
allOf:
- $ref: store-config.yaml
- type: object
  required:
  - connectorRef
  - repositoryName
  properties:
    artifactPaths:
      oneOf:
      - type: array
        items:
          type: string
      - type: string
        pattern: ^<\+input>((\.)((executionInput\(\))|(allowedValues|default|regex)\(.+?\)))*$
        minLength: 1
    connectorRef:
      type: string
    metadata:
      type: string
    repositoryName:
      type: string
$schema: http://json-schema.org/draft-07/schema#
properties:
  description:
    desc: This is the description for ArtifactoryStoreConfig
