title: AwsCloudProviderBasicConfig
allOf:
- $ref: cloud-provider-spec.yaml
- type: object
  required:
  - connectorRef
  - region
  properties:
    connectorRef:
      type: string
    region:
      type: string
$schema: http://json-schema.org/draft-07/schema#
properties:
  description:
    desc: This is the description for AwsCloudProviderBasicConfig
