title: AzureCreateARMResourceStepConfiguration
type: object
required:
- connectorRef
- scope
- template
properties:
  connectorRef:
    type: string
  parameters:
    $ref: azure-create-a-r-m-resource-parameter-file.yaml
  scope:
    $ref: azure-create-a-r-m-resource-step-scope.yaml
  template:
    $ref: azure-template-file.yaml
  description:
    desc: This is the description for AzureCreateARMResourceStepConfiguration
$schema: http://json-schema.org/draft-07/schema#
