title: AzureWebAppSlotDeploymentStepInfo
allOf:
- $ref: ../../common/step-spec-type.yaml
- type: object
  required:
  - deploymentSlot
  - webApp
  properties:
    clean:
      oneOf:
      - type: boolean
      - type: string
        pattern: (<\+.+>.*)
        minLength: 1
    skipSteadyStateCheck:
      oneOf:
      - type: boolean
      - type: string
        pattern: (<\+.+>.*)
        minLength: 1
    delegateSelectors:
      oneOf:
      - type: array
        items:
          type: string
      - type: string
        pattern: (<\+.+>.*)
        minLength: 1
    deploymentSlot:
      type: string
      minLength: 1
    webApp:
      type: string
      minLength: 1
$schema: http://json-schema.org/draft-07/schema#
type: object
required:
- deploymentSlot
- webApp
properties:
  clean:
    oneOf:
    - type: boolean
    - type: string
      pattern: (<\+.+>.*)
      minLength: 1
  skipSteadyStateCheck:
    oneOf:
    - type: boolean
    - type: string
      pattern: (<\+.+>.*)
      minLength: 1
  delegateSelectors:
    oneOf:
    - type: array
      items:
        type: string
    - type: string
      pattern: (<\+.+>.*)
      minLength: 1
  deploymentSlot:
    type: string
    minLength: 1
  webApp:
    type: string
    minLength: 1
  description:
    desc: This is the description for AzureWebAppSlotDeploymentStepInfo
