title: CloudformationCreateStackStepConfiguration
type: object
required:
- connectorRef
- region
- stackName
- templateFile
properties:
  capabilities:
    oneOf:
    - type: array
      items:
        type: string
    - type: string
  connectorRef:
    type: string
  parameterOverrides:
    type: array
    items:
      oneOf:
      - $ref: ../../common/number-ng-variable.yaml
      - $ref: ../../common/secret-ng-variable.yaml
      - $ref: ../../common/string-ng-variable.yaml
  parameters:
    type: array
    items:
      $ref: cloudformation-parameters-file-spec.yaml
  region:
    type: string
  roleArn:
    type: string
  skipOnStackStatuses:
    oneOf:
    - type: array
      items:
        type: string
    - type: string
  stackName:
    type: string
  tags:
    $ref: cloudformation-tags.yaml
  templateFile:
    $ref: cloudformation-template-file.yaml
  description:
    desc: This is the description for CloudformationCreateStackStepConfiguration
$schema: http://json-schema.org/draft-07/schema#
