title: CloudformationRollbackStepConfiguration
type: object
required:
- provisionerIdentifier
properties:
  provisionerIdentifier:
    type: string
  description:
    desc: This is the description for CloudformationRollbackStepConfiguration
$schema: http://json-schema.org/draft-07/schema#
