title: CreatePRStepUpdateConfigScriptWrapper
type: object
required:
- spec
- type
properties:
  type:
    type: string
  description:
    desc: This is the description for CreatePRStepUpdateConfigScriptWrapper
$schema: http://json-schema.org/draft-07/schema#
allOf:
- if:
    properties:
      type:
        const: Inline
  then:
    properties:
      spec:
        $ref: create-p-r-step-update-config-script-inline-source.yaml
