title: CustomRemoteStoreConfig
allOf:
- $ref: store-config.yaml
- type: object
  required:
  - extractionScript
  - filePath
  properties:
    delegateSelectors:
      oneOf:
      - type: array
        items:
          type: string
      - type: string
        pattern: ^<\+input>((\.)((executionInput\(\))|(allowedValues|default|regex)\(.+?\)))*$
        minLength: 1
    extractionScript:
      type: string
    filePath:
      type: string
$schema: http://json-schema.org/draft-07/schema#
properties:
  description:
    desc: This is the description for CustomRemoteStoreConfig
