title: HelmValues
type: object
properties:
  fileParameters:
    oneOf:
    - type: array
      items:
        $ref: helm-file-parameters.yaml
    - type: string
      pattern: ^<\+input>((\.)((executionInput\(\))|(allowedValues|default|regex)\(.+?\)))*$
      minLength: 1
  parameters:
    oneOf:
    - type: array
      items:
        $ref: helm-parameters.yaml
    - type: string
      pattern: ^<\+input>((\.)((executionInput\(\))|(allowedValues|default|regex)\(.+?\)))*$
      minLength: 1
  valueFiles:
    oneOf:
    - type: array
      items:
        type: string
    - type: string
      pattern: (<\+.+>.*)
      minLength: 1
  description:
    desc: This is the description for HelmValues
$schema: http://json-schema.org/draft-07/schema#
