title: InheritedCloudformationDeleteStackStepConfiguration
allOf:
- $ref: cloudformation-delete-stack-step-configuration-spec.yaml
- type: object
  required:
  - provisionerIdentifier
  properties:
    provisionerIdentifier:
      type: string
$schema: http://json-schema.org/draft-07/schema#
properties:
  description:
    desc: This is the description for InheritedCloudformationDeleteStackStepConfiguration
