title: InlineCloudformationDeleteStackStepConfiguration
allOf:
- $ref: cloudformation-delete-stack-step-configuration-spec.yaml
- type: object
  required:
  - connectorRef
  - region
  - stackName
  properties:
    connectorRef:
      type: string
    region:
      type: string
    roleArn:
      type: string
    stackName:
      type: string
$schema: http://json-schema.org/draft-07/schema#
properties:
  description:
    desc: This is the description for InlineCloudformationDeleteStackStepConfiguration
