title: ManifestConfigWrapper
type: object
properties:
  manifest:
    $ref: manifest-config.yaml
  description:
    desc: This is the description for step ManifestConfigWrapper
$schema: http://json-schema.org/draft-07/schema#
