title: OciHelmChartStoreConfigWrapper
type: object
required:
- spec
- type
properties:
  metadata:
    type: string
  type:
    type: string
    enum:
    - Generic
  description:
    desc: This is the description for OciHelmChartStoreConfigWrapper
$schema: http://json-schema.org/draft-07/schema#
allOf:
- if:
    properties:
      type:
        const: Generic
  then:
    properties:
      spec:
        $ref: oci-helm-chart-store-generic-config.yaml
