title: OciHelmChartConfig
allOf:
- $ref: store-config.yaml
- type: object
  properties:
    basePath:
      type: string
    config:
      $ref: oci-helm-chart-store-config-wrapper.yaml
    metadata:
      type: string
$schema: http://json-schema.org/draft-07/schema#
properties:
  description:
    desc: This is the description for OciHelmChartConfig
