title: OverlayConfiguration
type: object
required:
- kustomizeYamlFolderPath
properties:
  kustomizeYamlFolderPath:
    type: string
  description:
    desc: This is the description for step OverlayConfiguration
$schema: http://json-schema.org/draft-07/schema#
