title: S3StoreConfig
allOf:
- $ref: store-config.yaml
- type: object
  properties:
    bucketName:
      type: string
    connectorRef:
      type: string
    folderPath:
      type: string
    metadata:
      type: string
    paths:
      oneOf:
      - type: array
        items:
          type: string
      - type: string
        pattern: ^<\+input>((\.)((executionInput\(\))|(allowedValues|default|regex)\(.+?\)))*$
        minLength: 1
    region:
      type: string
$schema: http://json-schema.org/draft-07/schema#
properties:
  description:
    desc: This is the description for S3StoreConfig
