title: TerraformCloudCliStepConfiguration
type: object
properties:
  spec:
    $ref: terraform-cloud-cli-execution-data.yaml
  description:
    desc: This is the description for step TerraformCloudCliStepConfiguration
$schema: http://json-schema.org/draft-07/schema#
