title: TerraformStepConfiguration
type: object
required:
- type
properties:
  spec:
    $ref: terraform-execution-data.yaml
  type:
    type: string
    enum:
    - Inline
    - InheritFromPlan
    - InheritFromApply
  description:
    desc: This is the description for TerraformStepConfiguration
$schema: http://json-schema.org/draft-07/schema#
