title: ArtifactoryStoreConfig
allOf:
- $ref: store-config.yaml
- type: object
  required:
  - connector
  - repo
  properties:
    paths:
      oneOf:
      - type: array
        items:
          type: string
      - type: string
    connector:
      type: string
    metadata:
      type: string
    repo:
      type: string
      description: repository name
$schema: http://json-schema.org/draft-07/schema#