title: AwsAsgLoadBalancerConfigYaml
type: object
required:
  - loadBalancer
  - prodListener
  - prodListenerRuleArn
properties:
  loadBalancer:
    type: string
  prodListener:
    type: string
  prodListenerRuleArn:
    type: string
  stageListener:
    type: string
  stageListenerRuleArn:
    type: string
  description:
    desc: This is the description for AwsAsgLoadBalancerConfigYaml
$schema: http://json-schema.org/draft-07/schema#
