title: AwsLoadBalancerConfigYaml
allOf:
- $ref: load-balancer-spec.yaml
- type: object
  required:
  - loadBalancer
  - prodListenerPort
  - prodListenerRuleArn
  - stageListenerPort
  - stageListenerRuleArn
  properties:
    loadBalancer:
      type: string
    prodListenerPort:
      type: string
    prodListenerRuleArn:
      type: string
    stageListenerPort:
      type: string
    stageListenerRuleArn:
      type: string
$schema: http://json-schema.org/draft-07/schema#
properties:
  description:
    desc: This is the description for AwsLoadBalancerConfigYaml
