title: AzureCreateBPStepConfiguration
type: object
required:
- connectorRef
- scope
- template
properties:
  assignmentName:
    type: string
  connectorRef:
    type: string
  scope:
    type: string
    enum:
    - Subscription
    - ManagementGroup
  template:
    $ref: azure-template-file.yaml
  description:
    desc: This is the description for AzureCreateBPStepConfiguration
$schema: http://json-schema.org/draft-07/schema#
