title: CloudformationDeleteStackStepConfigurationSpec
type: object
discriminator: type
properties:
  type:
    type: string
  description:
    desc: This is the description for CloudformationDeleteStackStepConfigurationSpec
$schema: http://json-schema.org/draft-07/schema#
