title: CustomRemoteStoreConfig
allOf:
- $ref: store-config.yaml
- type: object
  required:
  - script
  - path
  properties:
    delegates:
      $ref: ../../common/delegate.yaml
    script:
      type: string
    path:
      type: string
      description: file path
$schema: http://json-schema.org/draft-07/schema#