title: GcsStoreConfig
allOf:
- $ref: store-config.yaml
- type: object
  properties:
    bucket:
      type: string
    connector:
      type: string
    folder:
      type: string
      description: folder path
    metadata:
      type: string
$schema: http://json-schema.org/draft-07/schema#