title: GcsStoreConfig
allOf:
- $ref: store-config.yaml
- type: object
  properties:
    bucketName:
      type: string
    connectorRef:
      type: string
    folderPath:
      type: string
    metadata:
      type: string
$schema: http://json-schema.org/draft-07/schema#
properties:
  description:
    desc: This is the description for GcsStoreConfig
