title: git_ops_application_source
type: object
properties:
  chart:
    description: Chart is a Helm chart name, and must be specified for applications sourced from a Helm repo.
    type: string
  helm:
    $ref: helm-values.yaml
  kustomize:
    $ref: kustomize-values.yaml
  path:
    description: Path is a directory path within the Git repository, and is only valid for applications sourced from Git.
    type: string
  ref:
    description: Ref is reference to another source within sources field. This field will not be used if used with a `source` tag.
    type: string
  repoURL:
    type: string
    title: RepoURL is the URL to the repository (Git or Helm) that contains the application manifests
  targetRevision:
    description: |-
      TargetRevision defines the revision of the source to sync the application to.
      In case of Git, this can be commit, tag, or branch. If omitted, will equal to HEAD.
      In case of Helm, this is a semver tag for the Chart's version.
    type: string
"$schema": http://json-schema.org/draft-07/schema#