title: HttpStoreConfig
allOf:
- $ref: store-config.yaml
- type: object
  properties:
    connector:
      type: string
    metadata:
      type: string
$schema: http://json-schema.org/draft-07/schema#