title: InheritFromManifestStoreConfig
allOf:
- $ref: store-config.yaml
- type: object
  properties:
    paths:
      oneOf:
      - type: array
        items:
          type: string
      - type: string
        pattern: ^<\+input>((\.)((executionInput\(\))|(allowedValues|default|regex)\(.+?\)))*$
        minLength: 1
$schema: http://json-schema.org/draft-07/schema#
properties:
  description:
    desc: This is the description for InheritFromManifestStoreConfig
