title: KustomizeValues
type: object
properties:
  images:
    oneOf:
      - type: array
        items:
          type: string
      - type: string
        pattern: ^<\+input>((\.)((executionInput\(\))|(allowedValues|default|regex)\(.+?\)))*$
        minLength: 1
  namespace:
    type: string
  replicas:
    oneOf:
      - type: array
        items:
          $ref: kustomize-replicas.yaml
      - type: string
        pattern: ^<\+input>((\.)((executionInput\(\))|(allowedValues|default|regex)\(.+?\)))*$
        minLength: 1
  description:
    desc: This is the description for KustomizeValues
$schema: http://json-schema.org/draft-07/schema#
