title: ManifestConfig
type: object
required:
- id
- spec
- type
properties:
  id:
    type: string
  type:
    type: string
    enum:
    - helm-chart
    - helm-repo-override
    - k8s-manifest
    - kustomize
    - kustomize-patches
    - openshift-param
    - openshift-template
    - values
    - serverless-aws-lambda
    - release-repo
    - deployment-repo
    - ecs-task-definition
    - ecs-service-definition
    - ecs-scalable-target-definition
    - ecs-scaling-policy-definition
    - tas-manifest
    - tas-vars
    - tas-auto-scaler
    - asg-launch-template
    - asg-configuration
    - asg-scaling-policy
    - asg-scheduled-update-group-action
    - google-cloud-function-definition
    - aws-lambda-function-definition
    - aws-lambda-function-alias-definition
    - aws-sam-directory
    - google-cloud-function-gen-one-definition
  description:
    desc: This is the description for ManifestConfig
$schema: http://json-schema.org/draft-07/schema#
allOf:
- if:
    properties:
      type:
        const: asg-configuration
  then:
    properties:
      spec:
        $ref: asg-configuration-manifest.yaml
- if:
    properties:
      type:
        const: asg-launch-template
  then:
    properties:
      spec:
        $ref: asg-launch-template-manifest.yaml
- if:
    properties:
      type:
        const: asg-scaling-policy
  then:
    properties:
      spec:
        $ref: asg-scaling-policy-manifest.yaml
- if:
    properties:
      type:
        const: asg-scheduled-update-group-action
  then:
    properties:
      spec:
        $ref: asg-scheduled-update-group-action-manifest.yaml
- if:
    properties:
      type:
        const: aws-lambda-function-alias-definition
  then:
    properties:
      spec:
        $ref: aws-lambda-function-alias-definition-manifest.yaml
- if:
    properties:
      type:
        const: aws-lambda-function-definition
  then:
    properties:
      spec:
        $ref: aws-lambda-definition-manifest.yaml
- if:
    properties:
      type:
        const: aws-sam-directory
  then:
    properties:
      spec:
        $ref: aws-sam-directory-manifest.yaml
- if:
    properties:
      type:
        const: deployment-repo
  then:
    properties:
      spec:
        $ref: git-ops-deployment-repo-manifest.yaml
- if:
    properties:
      type:
        const: ecs-scalable-target-definition
  then:
    properties:
      spec:
        $ref: ecs-scalable-target-definition-manifest.yaml
- if:
    properties:
      type:
        const: ecs-scaling-policy-definition
  then:
    properties:
      spec:
        $ref: ecs-scaling-policy-definition-manifest.yaml
- if:
    properties:
      type:
        const: ecs-service-definition
  then:
    properties:
      spec:
        $ref: ecs-service-definition-manifest.yaml
- if:
    properties:
      type:
        const: ecs-task-definition
  then:
    properties:
      spec:
        $ref: ecs-task-definition-manifest.yaml
- if:
    properties:
      type:
        const: google-cloud-function-definition
  then:
    properties:
      spec:
        $ref: google-cloud-function-definition-manifest.yaml
- if:
    properties:
      type:
        const: google-cloud-function-gen-one-definition
  then:
    properties:
      spec:
        $ref: google-cloud-function-gen-one-definition-manifest.yaml
- if:
    properties:
      type:
        const: helm-chart
  then:
    properties:
      spec:
        $ref: helm-chart-manifest.yaml
- if:
    properties:
      type:
        const: helm-repo-override
  then:
    properties:
      spec:
        $ref: helm-repo-override-manifest.yaml
- if:
    properties:
      type:
        const: k8s-manifest
  then:
    properties:
      spec:
        $ref: k8s-manifest.yaml
- if:
    properties:
      type:
        const: kustomize
  then:
    properties:
      spec:
        $ref: kustomize-manifest.yaml
- if:
    properties:
      type:
        const: kustomize-patches
  then:
    properties:
      spec:
        $ref: kustomize-patches-manifest.yaml
- if:
    properties:
      type:
        const: openshift-param
  then:
    properties:
      spec:
        $ref: openshift-param-manifest.yaml
- if:
    properties:
      type:
        const: openshift-template
  then:
    properties:
      spec:
        $ref: openshift-manifest.yaml
- if:
    properties:
      type:
        const: release-repo
  then:
    properties:
      spec:
        $ref: release-repo-manifest.yaml
- if:
    properties:
      type:
        const: serverless-aws-lambda
  then:
    properties:
      spec:
        $ref: serverless-aws-lambda-manifest.yaml
- if:
    properties:
      type:
        const: tas-auto-scaler
  then:
    properties:
      spec:
        $ref: auto-scaler-manifest.yaml
- if:
    properties:
      type:
        const: tas-manifest
  then:
    properties:
      spec:
        $ref: tas-manifest.yaml
- if:
    properties:
      type:
        const: tas-vars
  then:
    properties:
      spec:
        $ref: vars-manifest.yaml
- if:
    properties:
      type:
        const: values
  then:
    properties:
      spec:
        $ref: values-manifest.yaml
