title: OciHelmChartStoreEcrConfig
allOf:
- $ref: "#/definitions/OciHelmChartStoreConfig"
- type: object
  required:
    - connectorRef
    - region
  properties:
    connectorRef:
      type: string
    metadata:
      type: string
    region:
      type: string
    registryId:
      type: string
$schema: http://json-schema.org/draft-07/schema#
properties:
  description:
    desc: This is the description for OciHelmChartStoreEcrConfig
