title: OciHelmChartConfig
allOf:
- $ref: store-config.yaml
- type: object
  properties:
    path:
      type: string
      description: base path
    config:
      $ref: oci-helm-chart-store-config-wrapper.yaml
    metadata:
      type: string
$schema: http://json-schema.org/draft-07/schema#