title: RemoteTerragruntBackendConfigSpec
allOf:
- $ref: terragrunt-backend-config-spec.yaml
- type: object
  required:
  - store
  properties:
    store:
      $ref: store-config-wrapper.yaml
$schema: http://json-schema.org/draft-07/schema#
properties:
  description:
    desc: This is the description for RemoteTerragruntBackendConfigSpec
