title: S3StoreConfig
allOf:
- $ref: store-config.yaml
- type: object
  properties:
    bucket:
      type: string
    connector:
      type: string
    folder:
      type: string
      description: folder path
    metadata:
      type: string
    paths:
      oneOf:
      - type: array
        items:
          type: string
      - type: string
    region:
      type: string
$schema: http://json-schema.org/draft-07/schema#