title: S3UrlStoreConfig
allOf:
- $ref: store-config.yaml
- type: object
  required:
  - connector
  - region
  - urls
  properties:
    connector:
      type: string
    metadata:
      type: string
    region:
      type: string
    urls:
      oneOf:
      - type: array
        items:
          type: string
      - type: string
$schema: http://json-schema.org/draft-07/schema#
properties:
  description:
    desc: This is the description for S3UrlStoreConfig
