title: StoreConfigWrapper
type: object
required:
  - spec
  - type
properties:
  metadata:
    type: string
  type:
    type: string
    enum:
    - custom-remote
    - git
    - github
    - bitbucket
    - gitLab
    - http
    - s3
    - gcs
    - inline
    - artifactory
    - s3-url
    - inherit_from_manifest
    - harness
    - oci-helm-chart
    - azure-repo
$schema: http://json-schema.org/draft-07/schema#
allOf:
- if:
    properties:
      type:
        const: artifactory
  then:
    properties:
      spec:
        $ref: artifactory-store-config.yaml
- if:
    properties:
      type:
        const: azure-repo
  then:
    properties:
      spec:
        $ref: azure-repo-store.yaml
- if:
    properties:
      type:
        const: bitbucket
  then:
    properties:
      spec:
        $ref: bitbucket-store.yaml
- if:
    properties:
      type:
        const: custom-remote
  then:
    properties:
      spec:
        $ref: custom-remote-store-config.yaml
- if:
    properties:
      type:
        const: gcs
  then:
    properties:
      spec:
        $ref: gcs-store-config.yaml
- if:
    properties:
      type:
        const: git
  then:
    properties:
      spec:
        $ref: git-store.yaml
- if:
    properties:
      type:
        const: gitLab
  then:
    properties:
      spec:
        $ref: git-lab-store.yaml
- if:
    properties:
      type:
        const: github
  then:
    properties:
      spec:
        $ref: github-store.yaml
- if:
    properties:
      type:
        const: harness
  then:
    properties:
      spec:
        $ref: ../custom/harness-store.yaml
- if:
    properties:
      type:
        const: http
  then:
    properties:
      spec:
        $ref: http-store-config.yaml
- if:
    properties:
      type:
        const: inherit-from-manifest
  then:
    properties:
      spec:
        $ref: inherit-from-manifest-store-config.yaml
- if:
    properties:
      type:
        const: inline
  then:
    properties:
      spec:
        $ref: inline-store-config.yaml
- if:
    properties:
      type:
        const: oci-helm-chart
  then:
    properties:
      spec:
        $ref: oci-helm-chart-config.yaml
- if:
    properties:
      type:
        const: s3
  then:
    properties:
      spec:
        $ref: s3-store-config.yaml
- if:
    properties:
      type:
        const: s3-url
  then:
    properties:
      spec:
        $ref: s3-url-store-config.yaml
