title: TerragruntStepConfiguration
type: object
required:
- type
properties:
  commandFlags:
    type: array
    items:
      $ref: terragrunt-cli-option-flag.yaml
  spec:
    $ref: terragrunt-execution-data.yaml
  type:
    type: string
    enum:
    - Inline
    - InheritFromPlan
    - InheritFromApply
  description:
    desc: This is the description for TerragruntStepConfiguration
$schema: http://json-schema.org/draft-07/schema#
