title: TerraformStepConfiguration
type: object
required:
- type
properties:
  commandFlags:
    type: array
    items:
      $ref: terraform-cli-option-flag.yaml
  skipRefreshCommand:
    oneOf:
    - type: boolean
    - type: string
  spec:
    $ref: terraform-execution-data.yaml
  type:
    type: string
    enum:
    - Inline
    - InheritFromPlan
    - InheritFromApply
  skipStateStorage:
    oneOf:
    - type: boolean
    - type: string
  description:
    desc: This is the description for TerraformStepConfiguration
$schema: http://json-schema.org/draft-07/schema#
