title: TerraformCloudCliStepConfiguration
type: object
properties:
  commandFlags:
    type: array
    items:
      $ref: terraform-cli-option-flag.yaml
  spec:
    $ref: terraform-cloud-cli-execution-data.yaml
  skipStateStorage:
    oneOf:
    - type: boolean
    - type: string
  description:
    desc: This is the description for TerraformCloudCliStepConfiguration
$schema: http://json-schema.org/draft-07/schema#
