title: ConfiguredMonitoredServiceSpec
allOf:
- $ref: monitored-service-spec.yaml
- type: object
  required:
  - monitoredServiceRef
  properties:
    monitoredServiceRef:
      type: string
$schema: http://json-schema.org/draft-07/schema#
properties:
  description:
    desc: This is the description for ConfiguredMonitoredServiceSpec
