title: DefaultAndConfiguredMonitoredServiceSpec
type: object
properties:
  type:
    type: string
  description:
    desc: This is the description for DefaultAndConfiguredMonitoredServiceSpec
$schema: http://json-schema.org/draft-07/schema#
