title: DefaultAndConfiguredMonitoredServiceNode
type: object
required:
- spec
- type
properties:
  spec:
    $ref: default-and-configured-monitored-service-spec.yaml
  type:
    type: string
  description:
    desc: This is the description for DefaultAndConfiguredMonitoredServiceNode
$schema: http://json-schema.org/draft-07/schema#
allOf:
  - if:
      properties:
        type:
          const: Default
    then:
      properties:
        spec:
          $ref: default-monitored-service-spec.yaml
  - if:
      properties:
        type:
          const: Configured
    then:
      properties:
        spec:
          $ref: configured-monitored-service-spec.yaml