title: VerifyConfigurableProperty
type: object
required:
- name
- type
- value
properties:
  name:
    type: string
    enum:
    - deploymentStartTime
    - dataCollectionDuration
  type:
    type: string
  value:
    oneOf:
    - type: string
    - type: number
  description:
    desc: This is the description for VerifyConfigurableProperty
$schema: http://json-schema.org/draft-07/schema#
