template_types:
  - ./step/template.yaml
  - ./secretmanager/template.yaml
  - ./stage/template.yaml
  - ./pipeline/template.yaml

step_template_types:
  - ./step/wait_step.yaml

stage_template_types:
  - ./stage/custom/stage.yaml