template_types:
  - ./step/template.yaml
  - ./secretmanager/template.yaml
  - ./stage/template.yaml
  - ./pipeline/template.yaml
  - ./stepgroup/template.yaml
  - ./monitoredservice/template.yaml
  - ./artifactsourcetemplate/template.yaml
  - ./customdeployment/template.yaml
  - ./workspace/template.yaml
  - ./notification/template.yaml

step_template_types:
  - ../pipeline/steps/cd/asg-blue-green-deploy-step-node.yaml
  - ../pipeline/steps/cd/asg-blue-green-rollback-step-node.yaml
  - ../pipeline/steps/cd/asg-blue-green-swap-service-step-node.yaml
  - ../pipeline/steps/cd/asg-shift-traffic-step-node.yaml
  - ../pipeline/steps/cd/asg-canary-delete-step-node.yaml
  - ../pipeline/steps/cd/asg-canary-deploy-step-node.yaml
  - ../pipeline/steps/cd/asg-rolling-deploy-step-node.yaml
  - ../pipeline/steps/cd/asg-steady-state-step-node.yaml
  - ../pipeline/steps/cd/asg-rolling-rollback-step-node.yaml
  - ../pipeline/steps/cd/asg-setup-step-node.yaml
  - ../pipeline/steps/cd/asg-phased-deploy-step-node.yaml
  - ../pipeline/steps/cd/asg-rollback-step-node.yaml
  - ../pipeline/steps/cd/aws-lambda-deploy-step-node.yaml
  - ../pipeline/steps/cd/aws-lambda-rollback-step-node.yaml
  - ../pipeline/steps/cd/aws-sam-build-step-node.yaml
  - ../pipeline/steps/cd/aws-sam-deploy-step-node.yaml
  - ../pipeline/steps/cd/aws-sam-rollback-step-node.yaml
  - ../pipeline/steps/cd/azure-a-r-m-rollback-step-node.yaml
  - ../pipeline/steps/cd/azure-create-a-r-m-resource-step-node.yaml
  - ../pipeline/steps/cd/azure-create-b-p-step-node.yaml
  - ../pipeline/steps/cd/azure-web-app-rollback-step-node.yaml
  - ../pipeline/steps/cd/azure-function-rollback-step-node.yaml
  - ../pipeline/steps/cd/azure-web-app-slot-deployment-step-node.yaml
  - ../pipeline/steps/cd/azure-web-app-swap-slot-step-node.yaml
  - ../pipeline/steps/cd/azure-web-app-traffic-shift-step-node.yaml
  - ../pipeline/steps/cd/bamboo-build-step-node.yaml
  - ../pipeline/steps/cd/chaos-step-node.yaml
  - ../pipeline/steps/cd/cloudformation-create-stack-step-node.yaml
  - ../pipeline/steps/cd/cloudformation-delete-stack-step-node.yaml
  - ../pipeline/steps/cd/cloudformation-rollback-step-node.yaml
  - ../pipeline/steps/cd/command-step-node.yaml
  - ../pipeline/steps/cd/download-manifests-step-node.yaml
  - ../pipeline/steps/cd/ecs-blue-green-create-service-step-node.yaml
  - ../pipeline/steps/cd/ecs-blue-green-rollback-step-node.yaml
  - ../pipeline/steps/cd/ecs-blue-green-swap-target-groups-step-node.yaml
  - ../pipeline/steps/cd/ecs-canary-delete-step-node.yaml
  - ../pipeline/steps/cd/ecs-canary-deploy-step-node.yaml
  - ../pipeline/steps/cd/ecs-rolling-deploy-step-node.yaml
  - ../pipeline/steps/cd/ecs-rolling-rollback-step-node.yaml
  - ../pipeline/steps/cd/ecs-run-task-step-node.yaml
  - ../pipeline/steps/cd/ecs-upgrade-container-step-node.yaml
  - ../pipeline/steps/cd/ecs-service-setup-step-node.yaml
  - ../pipeline/steps/cd/ecs-basic-rollback-step-node.yaml
  - ../pipeline/steps/cd/elastigroup-b-g-stage-setup-step-node.yaml
  - ../pipeline/steps/cd/elastigroup-deploy-step-node.yaml
  - ../pipeline/steps/cd/elastigroup-rollback-step-node.yaml
  - ../pipeline/steps/cd/elastigroup-setup-step-node.yaml
  - ../pipeline/steps/cd/elastigroup-swap-route-step-node.yaml
  - ../pipeline/steps/cd/fetch-instance-script-step-node.yaml
  - ../pipeline/steps/cd/fetch-linked-apps-step-node.yaml
  - ../pipeline/steps/cd/google-functions-deploy-step-node.yaml
  - ../pipeline/steps/cd/google-functions-gen-one-deploy-step-node.yaml
  - ../pipeline/steps/cd/google-functions-deploy-without-traffic-step-node.yaml
  - ../pipeline/steps/cd/google-functions-rollback-step-node.yaml
  - ../pipeline/steps/cd/google-functions-traffic-shift-step-node.yaml
  - ../pipeline/steps/cd/helm-deploy-step-node.yaml
  - ../pipeline/steps/cd/helm-rollback-step-node.yaml
  - ../pipeline/steps/cd/helm-delete-step-node.yaml
  - ../pipeline/steps/cd/jenkins-build-step-node.yaml
  - ../pipeline/steps/cd/k8s-apply-step-node.yaml
  - ../pipeline/steps/cd/k8s-b-g-swap-services-step-node.yaml
  - ../pipeline/steps/cd/k8s-blue-green-step-node.yaml
  - ../pipeline/steps/cd/k8s-canary-delete-step-node.yaml
  - ../pipeline/steps/cd/k8s-canary-step-node.yaml
  - ../pipeline/steps/cd/k8s-delete-step-node.yaml
  - ../pipeline/steps/cd/k8s-dry-run-manifest-step-node.yaml
  - ../pipeline/steps/cd/k8s-rolling-rollback-step-node.yaml
  - ../pipeline/steps/cd/k8s-rolling-step-node.yaml
  - ../pipeline/steps/cd/k8s-scale-step-node.yaml
  - ../pipeline/steps/cd/merge-pr-step-node.yaml
  - ../pipeline/steps/cd/revert-pr-step-node.yaml
  - ../pipeline/steps/cd/azure-function-deploy-step-node.yaml
  - ../pipeline/steps/cd/azure-function-rollback-step-node.yaml
  - ../pipeline/steps/cd/serverless-aws-lambda-deploy-step-node.yaml
  - ../pipeline/steps/cd/serverless-aws-lambda-deploy-v2-step-node.yaml
  - ../pipeline/steps/cd/serverless-aws-lambda-package-v2-step-node.yaml
  - ../pipeline/steps/cd/serverless-aws-lambda-prepare-rollback-v2-step-node.yaml
  - ../pipeline/steps/cd/serverless-aws-lambda-rollback-step-node.yaml
  - ../pipeline/steps/cd/serverless-aws-lambda-rollback-v2-step-node.yaml
  - ../pipeline/steps/cd/shell-script-provision-step-node.yaml
  - ../pipeline/steps/cd/sync-step-node.yaml
  - ../pipeline/steps/cd/tas-app-resize-step-node.yaml
  - ../pipeline/steps/cd/tas-b-g-app-setup-step-node.yaml
  - ../pipeline/steps/cd/tas-basic-app-setup-step-node.yaml
  - ../pipeline/steps/cd/tas-canary-app-setup-step-node.yaml
  - ../pipeline/steps/cd/tas-command-step-node.yaml
  - ../pipeline/steps/cd/tas-route-mapping-step-node.yaml
  - ../pipeline/steps/cd/tas-rollback-step-node.yaml
  - ../pipeline/steps/cd/tas-rolling-deploy-step-node.yaml
  - ../pipeline/steps/cd/tas-rolling-rollback-step-node.yaml
  - ../pipeline/steps/cd/tas-swap-rollback-step-node.yaml
  - ../pipeline/steps/cd/tas-swap-routes-step-node.yaml
  - ../pipeline/steps/cd/terraform-apply-step-node.yaml
  - ../pipeline/steps/cd/terraform-cloud-rollback-step-node.yaml
  - ../pipeline/steps/cd/terraform-cloud-run-step-node.yaml
  - ../pipeline/steps/cd/terraform-destroy-step-node.yaml
  - ../pipeline/steps/cd/terraform-plan-step-node.yaml
  - ../pipeline/steps/cd/terraform-rollback-step-node.yaml
  - ../pipeline/steps/cd/terragrunt-apply-step-node.yaml
  - ../pipeline/steps/cd/terragrunt-destroy-step-node.yaml
  - ../pipeline/steps/cd/terragrunt-plan-step-node.yaml
  - ../pipeline/steps/cd/terragrunt-rollback-step-node.yaml
  - ../pipeline/steps/cd/update-release-repo-step-node.yaml
  - ../pipeline/steps/ci/artifactory-upload-node.yaml
  - ../pipeline/steps/ci/bitrise-step-node.yaml
  - ../pipeline/steps/ci/build-and-push-acrnode.yaml
  - ../pipeline/steps/ci/build-and-push-docker-node.yaml
  - ../pipeline/steps/ci/build-and-push-ecrnode.yaml
  - ../pipeline/steps/ci/build-and-push-gcrnode.yaml
  - ../pipeline/steps/ci/build-and-push-garnode.yaml
  - ../pipeline/steps/ci/gcsupload-node.yaml
  - ../pipeline/steps/ci/git-clone-step-node.yaml
  - ../pipeline/steps/ci/restore-cache-gcsnode.yaml
  - ../pipeline/steps/ci/restore-cache-s3-node.yaml
  - ../pipeline/steps/ci/run-test-step-node.yaml
  - ../pipeline/steps/ci/s3-upload-node.yaml
  - ../pipeline/steps/ci/save-cache-gcsnode.yaml
  - ../pipeline/steps/ci/save-cache-s3-node.yaml
  - ../pipeline/steps/idp/idpcookiecutter-node.yaml
  - ../pipeline/steps/idp/idpcreatecatalog-node.yaml
  - ../pipeline/steps/idp/idpcreateorganisation-node.yaml
  - ../pipeline/steps/idp/idpcreateproject-node.yaml
  - ../pipeline/steps/idp/idpcreaterepo-node.yaml
  - ../pipeline/steps/idp/idpcreateresource-node.yaml
  - ../pipeline/steps/idp/idpdirectpush-node.yaml
  - ../pipeline/steps/idp/idpregistercatalog-node.yaml
  - ../pipeline/steps/idp/idpslacknotify-node.yaml
  - ../pipeline/steps/idp/idpupdatecatalogproperty-node.yaml
  - ../pipeline/steps/common/ssca-enforcement-step-node.yaml
  - ../pipeline/steps/common/ssca-orchestration-step-node.yaml
  - ../pipeline/steps/common/action-step-node.yaml
  - ../pipeline/steps/common/anchore-scan-node.yaml
  - ../pipeline/steps/common/aqua-security-scan-node.yaml
  - ../pipeline/steps/common/aqua-trivy-scan-node.yaml
  - ../pipeline/steps/common/aws-ecr-scan-node.yaml
  - ../pipeline/steps/common/aws-security-hub-scan-node.yaml
  - ../pipeline/steps/common/background-step-node.yaml
  - ../pipeline/steps/common/bandit-scan-node.yaml
  - ../pipeline/steps/common/black-duck-scan-node.yaml
  - ../pipeline/steps/common/brakeman-scan-node.yaml
  - ../pipeline/steps/common/burp-scan-node.yaml
  - ../pipeline/steps/common/checkmarx-scan-node.yaml
  - ../pipeline/steps/common/checkmarx-one-scan-node.yaml
  - ../pipeline/steps/common/checkov-scan-node.yaml
  - ../pipeline/steps/common/clair-scan-node.yaml
  - ../pipeline/steps/common/codeql-scan-node.yaml
  - ../pipeline/steps/common/coverity-scan-node.yaml
  - ../pipeline/steps/common/custom-ingest-scan-node.yaml
  - ../pipeline/steps/common/data-theorem-scan-node.yaml
  - ../pipeline/steps/common/docker-content-trust-scan-node.yaml
  - ../pipeline/steps/common/fortify-on-demand-scan-node.yaml
  - ../pipeline/steps/common/fossa-scan-node.yaml
  - ../pipeline/steps/common/gitleaks-scan-node.yaml
  - ../pipeline/steps/common/grype-scan-node.yaml
  - ../pipeline/steps/common/jfrog-xray-scan-node.yaml
  - ../pipeline/steps/common/mend-scan-node.yaml
  - ../pipeline/steps/common/metasploit-scan-node.yaml
  - ../pipeline/steps/common/nessus-scan-node.yaml
  - ../pipeline/steps/common/nexus-iqscan-node.yaml
  - ../pipeline/steps/common/nikto-scan-node.yaml
  - ../pipeline/steps/common/nmap-scan-node.yaml
  - ../pipeline/steps/common/openvas-scan-node.yaml
  - ../pipeline/steps/common/osv-scanner-scan-node.yaml
  - ../pipeline/steps/common/owasp-scan-node.yaml
  - ../pipeline/steps/common/plugin-step-node.yaml
  - ../pipeline/steps/common/prisma-cloud-scan-node.yaml
  - ../pipeline/steps/common/prowler-scan-node.yaml
  - ../pipeline/steps/common/qualys-scan-node.yaml
  - ../pipeline/steps/common/reapsaw-scan-node.yaml
  - ../pipeline/steps/common/run-step-node.yaml
  - ../pipeline/steps/common/security-node.yaml
  - ../pipeline/steps/common/semgrep-scan-node.yaml
  - ../pipeline/steps/common/shift-left-scan-node.yaml
  - ../pipeline/steps/common/sniper-scan-node.yaml
  - ../pipeline/steps/common/snyk-scan-node.yaml
  - ../pipeline/steps/common/sonarqube-scan-node.yaml
  - ../pipeline/steps/common/sysdig-scan-node.yaml
  - ../pipeline/steps/common/tenable-scan-node.yaml
  - ../pipeline/steps/common/traceable-scan-node.yaml
  - ../pipeline/steps/common/veracode-scan-node.yaml
  - ../pipeline/steps/common/zap-scan-node.yaml
  - ../pipeline/steps/custom/barrier-step-node.yaml
  - ../pipeline/steps/custom/container-step-node.yaml
  - ../pipeline/steps/custom/custom-approval-step-node.yaml
  - ../pipeline/steps/custom/email-step-node.yaml
  - ../pipeline/steps/custom/flag-configuration-step-node.yaml
  - ../pipeline/steps/custom/harness-approval-step-node.yaml
  - ../pipeline/steps/custom/http-step-node.yaml
  - ../pipeline/steps/custom/jira-approval-step-node.yaml
  - ../pipeline/steps/custom/jira-create-step-node.yaml
  - ../pipeline/steps/custom/jira-update-step-node.yaml
  - ../pipeline/steps/custom/policy-step-node.yaml
  - ../pipeline/steps/custom/queue-step-node.yaml
  - ../pipeline/steps/custom/service-now-approval-step-node.yaml
  - ../pipeline/steps/custom/service-now-create-step-node.yaml
  - ../pipeline/steps/custom/service-now-import-set-step-node.yaml
  - ../pipeline/steps/custom/service-now-update-step-node.yaml
  - ../pipeline/steps/custom/shell-script-step-node.yaml
  - ../pipeline/steps/custom/template-step-node.yaml
  - ../pipeline/steps/custom/wait-step-node.yaml
  - ../pipeline/steps/cvng/cv-analyze-deployment-step-node.yaml
  - ../pipeline/steps/cvng/cv-verify-step-node.yaml
  - ../pipeline/steps/iacm/iacmapproval-step-node.yaml
  - ../pipeline/steps/iacm/iacmterraform-plugin-step-node.yaml
  - ../pipeline/steps/iacm/iacmopentofu-plugin-step-node.yaml
  - ../pipeline/steps/iacm/iacmmoduletest-plugin-step-node.yaml
  - ../pipeline/steps/common/aws-cdk-bootstrap-step-node.yaml
  - ../pipeline/steps/common/aws-cdk-synth-step-node.yaml
  - ../pipeline/steps/common/aws-cdk-diff-step-node.yaml
  - ../pipeline/steps/cd/k8s-bgstage-scale-down-step-node.yaml
  - ../pipeline/steps/cd/google-functions-gen-one-rollback-step-node.yaml
  - ../pipeline/stages/cd/custom-deployment-config.yaml
  - ../pipeline/steps/common/aws-cdk-deploy-step-node.yaml
  - ../pipeline/steps/common/dbops-apply-schema-step-node.yaml
  - ../pipeline/steps/common/dbops-rollback-schema-step-node.yaml
  - ../pipeline/steps/common/aws-cdk-destroy-step-node.yaml
  - ../pipeline/steps/common/aws-cdk-rollback-step-node.yaml
  - ../pipeline/steps/cd/update-git-ops-app-step-node.yaml
  - ../pipeline/steps/common/slsa-verification-step-node.yaml
  - ../pipeline/steps/cd/k8s-traffic-routing-step-node.yaml
  - ../pipeline/steps/cd/download-aws-s3-step-node.yaml
  - ../pipeline/steps/cd/download-harness-store-step-node.yaml
  - ../pipeline/steps/common/wiz-scan-node.yaml
  - ../pipeline/steps/iacm/iacmcheckov-plugin-step-node.yaml
  - ../pipeline/steps/iacm/iacmtfcompliance-plugin-step-node.yaml
  - ../pipeline/steps/iacm/iacmtflint-plugin-step-node.yaml
  - ../pipeline/steps/iacm/iacmtfsec-plugin-step-node.yaml
  - ../pipeline/steps/cd/gitops-get-app-details-step-node.yaml
  - ../pipeline/steps/common/dbops-liquibase-command-step-node.yaml
  - ../pipeline/steps/common/files-upload-step-node.yaml
  - ../pipeline/steps/cd/google-cloud-run-prepare-rollback-data-step-node.yaml
  - ../pipeline/steps/cd/google-cloud-run-deploy-step-node.yaml
  - ../pipeline/steps/cd/google-cloud-run-traffic-shift-step-node.yaml
  - ../pipeline/steps/cd/google-cloud-run-rollback-step-node.yaml
  - ../pipeline/steps/cd/google-cloud-run-job-step-node.yaml
  - ../pipeline/steps/custom/event-listener-step-node.yaml

stage_template_types:
  - ../pipeline/stages/custom/custom-stage-node.yaml
  - ../pipeline/stages/approval/approval-stage-node.yaml
  - ../pipeline/stages/cd/deployment-stage-node.yaml
  - ../pipeline/stages/ci/integration-stage-node.yaml
  - ../pipeline/stages/cf/feature-flag-stage-node.yaml
  - ../pipeline/stages/security/security-stage-node.yaml
  - ../pipeline/stages/template/template-stage-node.yaml
  - ../pipeline/stages/iacm/iacmstage-node.yaml
  - ../pipeline/stages/idp/idpstage-node.yaml

artifact_source_template_types:
  - ../pipeline/stages/cd/artifact-source.yaml

custom_deployment_template_types:
  - ../pipeline/stages/cd/custom-deployment-config.yaml
# TODO: @PrashantSharma @UtkarshChoubey
# We were adding schema for different stageTypes as for Stepgroup Templates
# Since this is not working currently we have assigned Object for Spec for Stepgroup Template
# We need to fix this to use the actual ConfigRef ( Currently it is matching multiple schemas when adding)

custom_step_group_template_types:
  - ../pipeline/stages/custom/step-group-element-config.yaml
  
deployment_step_group_template_types:
  - ../pipeline/stages/cd/step-group-element-config.yaml
  
