template_types:
  - ./step/template.yaml
  - ./secretmanager/template.yaml
  - ./stage/template.yaml
  - ./pipeline/template.yaml

step_template_types:
  - ../pipeline/steps/pie/wait-step-node.yaml
  - ../pipeline/steps/pie/harness-approval-step-node.yaml
  - ../pipeline/steps/pie/service-now-create-step-node.yaml
  - ../pipeline/steps/pie/jira-update-step-node.yaml
  - ../pipeline/steps/pie/barrier-step-node.yaml
  - ../pipeline/steps/pie/custom-approval-step-node.yaml
  - ../pipeline/steps/pie/template-step-node.yaml
  - ../pipeline/steps/pie/policy-step-node.yaml
  - ../pipeline/steps/pie/service-now-import-set-step-node.yaml
  - ../pipeline/steps/pie/http-step-node.yaml
  - ../pipeline/steps/pie/shell-script-step-node.yaml
  - ../pipeline/steps/pie/wait-step-node.yaml
  - ../pipeline/steps/pie/container-step-node.yaml
  - ../pipeline/steps/pie/jira-create-step-node.yaml
  - ../pipeline/steps/pie/email-step-node.yaml
  - ../pipeline/steps/pie/queue-step-node.yaml
  - ../pipeline/steps/pie/service-now-update-step-node.yaml
  - ../pipeline/steps/pie/flag-configuration-step-node.yaml
  - ../pipeline/steps/pie/service-now-approval-step-node.yaml
  - ../pipeline/steps/pie/jira-approval-step-node.yaml
  - ../pipeline/steps/cvng/cv-verify-step-node.yaml
  - ../pipeline/steps/common/background-step-node.yaml
  - ../pipeline/steps/common/run-step-node.yaml
  - ../pipeline/steps/ci/bitrise-step-node.yaml
  - ../pipeline/steps/ci/run-test-step-node.yaml
  - ../pipeline/steps/ci/plugin-step-node.yaml
  - ../pipeline/steps/ci/ssca-orchestration-step-node.yaml
  - ../pipeline/steps/ci/git-clone-step-node.yaml
  - ../pipeline/steps/ci/action-step-node.yaml
  - ../pipeline/steps/cd/aws-sam-rollback-step-node.yaml
  - ../pipeline/steps/cd/azure-web-app-swap-slot-step-node.yaml
  - ../pipeline/steps/cd/terraform-rollback-step-node.yaml
  - ../pipeline/steps/cd/cloudformation-rollback-step-node.yaml
  - ../pipeline/steps/cd/terragrunt-destroy-step-node.yaml
  - ../pipeline/steps/cd/k8s-blue-green-step-node.yaml
  - ../pipeline/steps/cd/azure-create-b-p-step-node.yaml
  - ../pipeline/steps/cd/google-functions-rollback-step-node.yaml
  - ../pipeline/steps/cd/ecs-run-task-step-node.yaml
  - ../pipeline/steps/cd/azure-web-app-rollback-step-node.yaml
  - ../pipeline/steps/cd/elastigroup-b-g-stage-setup-step-node.yaml
  - ../pipeline/steps/cd/cloudformation-create-stack-step-node.yaml
  - ../pipeline/steps/cd/helm-deploy-step-node.yaml
  - ../pipeline/steps/cd/tas-app-resize-step-node.yaml
  - ../pipeline/steps/cd/azure-create-a-r-m-resource-step-node.yaml
  - ../pipeline/steps/cd/tas-rollback-step-node.yaml
  - ../pipeline/steps/cd/tas-rolling-deploy-step-node.yaml
  - ../pipeline/steps/cd/ecs-rolling-deploy-step-node.yaml
  - ../pipeline/steps/cd/k8s-b-g-swap-services-step-node.yaml
  - ../pipeline/steps/cd/terragrunt-rollback-step-node.yaml
  - ../pipeline/steps/cd/azure-a-r-m-rollback-step-node.yaml
  - ../pipeline/steps/cd/serverless-aws-lambda-rollback-step-node.yaml
  - ../pipeline/steps/cd/chaos-step-node.yaml
  - ../pipeline/steps/cd/cloudformation-delete-stack-step-node.yaml
  - ../pipeline/steps/cd/ecs-blue-green-rollback-step-node.yaml
  - ../pipeline/steps/cd/elastigroup-rollback-step-node.yaml
  - ../pipeline/steps/cd/aws-lambda-rollback-step-node.yaml
  - ../pipeline/steps/cd/google-functions-deploy-without-traffic-step-node.yaml
  - ../pipeline/steps/cd/google-functions-deploy-step-node.yaml
  - ../pipeline/steps/cd/tas-swap-rollback-step-node.yaml
  - ../pipeline/steps/cd/bamboo-build-step-node.yaml
  - ../pipeline/steps/cd/asg-rolling-rollback-step-node.yaml
  - ../pipeline/steps/cd/ecs-rolling-rollback-step-node.yaml
  - ../pipeline/steps/cd/elastigroup-deploy-step-node.yaml
  - ../pipeline/steps/cd/terraform-plan-step-node.yaml
  - ../pipeline/steps/cd/terraform-apply-step-node.yaml
  - ../pipeline/steps/cd/aws-lambda-deploy-step-node.yaml
  - ../pipeline/steps/cd/tas-canary-app-setup-step-node.yaml
  - ../pipeline/steps/cd/ecs-blue-green-swap-target-groups-step-node.yaml
  - ../pipeline/steps/cd/create-p-r-step-node.yaml
  - ../pipeline/steps/cd/helm-rollback-step-node.yaml
  - ../pipeline/steps/cd/terragrunt-plan-step-node.yaml
  - ../pipeline/steps/cd/asg-canary-delete-step-node.yaml
  - ../pipeline/steps/cd/asg-blue-green-swap-service-step-node.yaml
  - ../pipeline/steps/cd/azure-web-app-traffic-shift-step-node.yaml
  - ../pipeline/steps/cd/terragrunt-apply-step-node.yaml
  - ../pipeline/steps/cd/k8s-rolling-rollback-step-node.yaml
  - ../pipeline/steps/cd/tas-b-g-app-setup-step-node.yaml
  - ../pipeline/steps/cd/merge-pr-step-node.yaml
  - ../pipeline/steps/cd/azure-web-app-slot-deployment-step-node.yaml
  - ../pipeline/steps/cd/terraform-destroy-step-node.yaml
  - ../pipeline/steps/cd/k8s-apply-step-node.yaml
  - ../pipeline/steps/cd/fetch-linked-apps-step-node.yaml
  - ../pipeline/steps/cd/ecs-canary-delete-step-node.yaml
  - ../pipeline/steps/cd/k8s-delete-step-node.yaml
  - ../pipeline/steps/cd/asg-blue-green-rollback-step-node.yaml
  - ../pipeline/steps/cd/k8s-scale-step-node.yaml
  - ../pipeline/steps/cd/k8s-dry-run-manifest-step-node.yaml
  - ../pipeline/steps/cd/k8s-rolling-step-node.yaml
  - ../pipeline/steps/cd/shell-script-provision-step-node.yaml
  - ../pipeline/steps/cd/command-step-node.yaml
  - ../pipeline/steps/cd/asg-blue-green-deploy-step-node.yaml
  - ../pipeline/steps/cd/update-release-repo-step-node.yaml
  - ../pipeline/steps/cd/tas-command-step-node.yaml
  - ../pipeline/steps/cd/ecs-blue-green-create-service-step-node.yaml
  - ../pipeline/steps/cd/google-functions-traffic-shift-step-node.yaml
  - ../pipeline/steps/cd/asg-canary-deploy-step-node.yaml
  - ../pipeline/steps/cd/k8s-canary-delete-step-node.yaml
  - ../pipeline/steps/cd/elastigroup-swap-route-step-node.yaml
  - ../pipeline/steps/cd/sync-step-node.yaml
  - ../pipeline/steps/cd/tas-rolling-rollback-step-node.yaml
  - ../pipeline/steps/cd/tas-basic-app-setup-step-node.yaml
  - ../pipeline/steps/cd/k8s-canary-step-node.yaml
  - ../pipeline/steps/cd/serverless-aws-lambda-deploy-step-node.yaml
  - ../pipeline/steps/cd/elastigroup-setup-step-node.yaml
  - ../pipeline/steps/cd/ecs-canary-deploy-step-node.yaml
  - ../pipeline/steps/cd/fetch-instance-script-step-node.yaml
  - ../pipeline/steps/cd/terraform-cloud-run-step-node.yaml
  - ../pipeline/steps/cd/jenkins-build-step-node.yaml
  - ../pipeline/steps/cd/tas-swap-routes-step-node.yaml
  - ../pipeline/steps/cd/asg-rolling-deploy-step-node.yaml
  - ../pipeline/steps/cd/terraform-cloud-rollback-step-node.yaml
  - ../pipeline/steps/cd/aws-sam-deploy-step-node.yaml

stage_template_types:
  - ../pipeline/stages/custom/custom-stage-node.yaml
  - ../pipeline/stages/approval/approval-stage-node.yaml
  - ../pipeline/stages/cd/deployment-stage-node.yaml
  - ../pipeline/stages/ci/integration-stage-node.yaml
  - ../pipeline/stages/cf/feature-flag-stage-node.yaml
  - ../pipeline/stages/pie/pipeline-stage-node.yaml
  - ../pipeline/stages/security/security-stage-node.yaml
  - ../pipeline/stages/template/template-stage-node.yaml